import type { PreviewJob } from '@/lib/domain/types';

export const INDEPENDENT_BERLIN_LISTINGS: PreviewJob[] = [
  // --------------------------------------------------------------------------
  // 1. CAFÉ & BARISTA
  // --------------------------------------------------------------------------
  {
    id: 'ind-cafe-01',
    slug: 'barista-specialty-coffee-bonanza-kreuzberg',
    title: 'Barista (m/w/d) für Specialty Coffee',
    company: 'Kiezrösterei & Café Paul',
    district: 'Kreuzberg',
    postcode: '10999',
    industryId: 'cafe',
    roleFamilyId: 'barista',
    employmentForms: ['Teilzeit', 'Minijob (bis 603 €)'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Direkt vom Betrieb',
    sourceUrl: '',
    whatsapp: '+4917642819034',
    phone: '+493061208941',
    compensation: {
      label: '16,50 € / Std. + Trinkgeld',
      amountMin: 16.5,
      amountMax: 16.5,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Bar-Trinkgeld anteilig (~3-5 €/h extra)',
    },
    hours: {
      label: '15–20 Std. / Woche',
      minimum: 15,
      maximum: 20,
      period: 'week',
    },
    schedule: {
      summary: 'Frühschichten (07:30–14:00) oder Nachmittagsschichten (13:30–19:00)',
      workDays: ['Di', 'Mi', 'Do', 'Sa', 'So'],
      timeWindows: ['07:30–14:00', '13:30–19:00'],
      startDate: 'Sofort',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Oranienstraße 42, 10999 Berlin-Kreuzberg',
    },
    responsibilities: [
      'Zubereitung von Espresso- und Filterkaffeespezialitäten (La Marzocco)',
      'Latte Art und Gästebetreuung an der Theke',
      'Kassensystem bedienen und Kuchenausgabe',
      'Mahlgrad-Einstellung und Pflege der Mühlen',
    ],
    requirements: [
      'Erste Barista-Erfahrung oder Begeisterung für guten Kaffee',
      'Freundliches, offenes Auftreten im Kiez',
      'Zuverlässigkeit und Teamgeist',
      'Deutsch oder fließendes Englisch',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'hallo@cafepaul-kreuzberg.de',
      deadline: null,
      contactName: 'Paulina Weber',
      instructions: 'Schreib uns kurz per WhatsApp oder E-Mail mit 2-3 Sätzen zu dir. Kein formeller Lebenslauf nötig!',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Barista', 'Specialty Coffee', 'Kreuzberg', 'Trinkgeld', 'Latte Art'],
    evidenceNotes: ['100% Unabhängiger Betrieb', 'Direktkontakt Inhaber:in', 'Faire Bezahlung'],
  },
  {
    id: 'ind-cafe-02',
    slug: 'service-theke-cafe-kollwitzplatz-prenzlberg',
    title: 'Café-Allrounder & Service (m/w/d)',
    company: 'Café Mirabelle am Kollwitzplatz',
    district: 'Prenzlauer Berg',
    postcode: '10435',
    industryId: 'cafe',
    roleFamilyId: 'service',
    employmentForms: ['Minijob (bis 603 €)', 'Werkstudent:in'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Direkt vom Betrieb',
    sourceUrl: '',
    whatsapp: '+491729012488',
    phone: '+493044031902',
    compensation: {
      label: '15,50 € / Std. + Trinkgeld',
      amountMin: 15.5,
      amountMax: 15.5,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Gutes Trinkgeld am Wochenende',
    },
    hours: {
      label: '10–15 Std. / Woche',
      minimum: 10,
      maximum: 15,
      period: 'week',
    },
    schedule: {
      summary: 'Wochenendschichten (Sa/So) oder 2 Wochentage nach Absprache',
      workDays: ['Fr', 'Sa', 'So'],
      timeWindows: ['09:00–16:00'],
      startDate: 'Ab sofort',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Kollwitzstraße 58, 10435 Berlin',
    },
    responsibilities: [
      'Gäste begrüßen, Bestellungen aufnehmen und servieren',
      'Zubereitung von Getränken und Frühstücksplatten',
      'Thekenpflege und Abräumen',
    ],
    requirements: [
      'Herzliche Gastgeber-Mentalität',
      'Pünktlich & verlässlich',
      'Grundkenntnisse Deutsch',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'team@cafe-mirabelle.berlin',
      deadline: null,
      contactName: 'Marc',
      instructions: 'WhatsApp-Nachricht genügt — oder komm einfach kurz auf einen Espresso vorbei.',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Service', 'Café', 'Prenzlauer Berg', 'Wochenende', 'Kollwitzplatz'],
    evidenceNotes: ['Familiengeführtes Café', 'Direktkontakt'],
  },
  {
    id: 'ind-cafe-03',
    slug: 'baeckerei-verkaeuferin-bio-manufaktur-neukoelln',
    title: 'Verkauf & Theke in Bio-Handwerksbäckerei',
    company: 'Brotkultur Neukölln',
    district: 'Neukölln',
    postcode: '12047',
    industryId: 'cafe',
    roleFamilyId: 'retail',
    employmentForms: ['Teilzeit', 'Minijob (bis 603 €)'],
    language: 'german_explicit',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Direkt vom Betrieb',
    sourceUrl: '',
    whatsapp: '+4917688201944',
    phone: '+493062729011',
    compensation: {
      label: '16,00 € / Std. + Personalrabatt',
      amountMin: 16.0,
      amountMax: 16.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: '50% Rabatt auf alle Backwaren',
    },
    hours: {
      label: '12–18 Std. / Woche',
      minimum: 12,
      maximum: 18,
      period: 'week',
    },
    schedule: {
      summary: 'Frühschichten ab 06:30 Uhr oder Nachmittage',
      workDays: ['Mi', 'Do', 'Fr', 'Sa'],
      timeWindows: ['06:30–12:30', '12:30–18:30'],
      startDate: 'Sofort',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Weserstraße 188, 12047 Berlin',
    },
    responsibilities: [
      'Verkauf von Sauerteigbroten, Gebäck und Kaffeespezialitäten',
      'Kundenberatung zu Zutaten und Allergenen',
      'Thekenpräsentation und Kassenführung',
    ],
    requirements: [
      'Freude am Umgang mit Menschen & Begeisterung für Handwerksbrot',
      'Gute Deutschkenntnisse für Kundengespräche',
      'Zuverlässigkeit am Morgen',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'hallo@brotkultur-neukoelln.de',
      deadline: null,
      contactName: 'Sebastian & Lena',
      instructions: 'Ruf kurz an oder schreib uns eine WhatsApp-Nachricht.',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Bäckerei', 'Bio', 'Handwerk', 'Neukölln', 'Sauerteig'],
    evidenceNotes: ['Unabhängige Bäckerei', 'Direktanstellung'],
  },
  {
    id: 'ind-cafe-04',
    slug: 'barista-matcha-bar-mitte',
    title: 'Barista & Matcha Barista (w/m/d)',
    company: 'Matcha & Bean Lab',
    district: 'Mitte',
    postcode: '10115',
    industryId: 'cafe',
    roleFamilyId: 'barista',
    employmentForms: ['Teilzeit', 'Werkstudent:in'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Direkt vom Betrieb',
    sourceUrl: '',
    whatsapp: '+4915178291044',
    phone: '+493028049182',
    compensation: {
      label: '17,00 € / Std. + Trinkgeld',
      amountMin: 17.0,
      amountMax: 17.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Free Specialty Drinks während der Schicht',
    },
    hours: {
      label: '15–20 Std. / Woche',
      minimum: 15,
      maximum: 20,
      period: 'week',
    },
    schedule: {
      summary: 'Flexible Schichten montags bis samstags',
      workDays: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
      timeWindows: ['08:00–14:00', '13:00–18:30'],
      startDate: 'Nächste Woche',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Torstraße 74, 10115 Berlin-Mitte',
    },
    responsibilities: [
      'Zubereitung von ceremonial Grade Matcha & Specialty Coffee',
      'Beratung der Gäste zu Teesorten und Röstungen',
      'Thekenorganisation und Bestandsaufnahme',
    ],
    requirements: [
      'Vorkenntnisse an der Siebträgermaschine erwünscht',
      'Interesse an Tee- & Kaffeekultur',
      'Englisch fließend, Deutsch von Vorteil',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'jobs@matchabean-berlin.de',
      deadline: null,
      contactName: 'Yuki & Alex',
      instructions: 'WhatsApp oder E-Mail mit Instagram/Portfolio oder kurzer Info genügt.',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Matcha', 'Barista', 'Mitte', 'Torstraße', 'Specialty'],
    evidenceNotes: ['Indie Concept Store & Café', 'Direktkontakt'],
  },

  // --------------------------------------------------------------------------
  // 2. GASTRO & BAR
  // --------------------------------------------------------------------------
  {
    id: 'ind-gastro-01',
    slug: 'servicekraft-weinbistro-kreuzberg',
    title: 'Servicekraft (m/w/d) im Naturwein-Bistro',
    company: 'Bistro Vin & Co.',
    district: 'Kreuzberg',
    postcode: '10967',
    industryId: 'gastro',
    roleFamilyId: 'service',
    employmentForms: ['Teilzeit', 'Minijob (bis 603 €)'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Direkt vom Betrieb',
    sourceUrl: '',
    whatsapp: '+4917699381022',
    phone: '+493069502911',
    compensation: {
      label: '16,00 € / Std. + 4–7 € Trinkgeld/h',
      amountMin: 16.0,
      amountMax: 16.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Hohes Trinkgeld, warmes Teamessen vor Service',
    },
    hours: {
      label: '2–3 Abende / Woche (12–18h)',
      minimum: 12,
      maximum: 18,
      period: 'week',
    },
    schedule: {
      summary: 'Abendschichten von 17:00 bis ca. 23:30 Uhr',
      workDays: ['Mi', 'Do', 'Fr', 'Sa'],
      timeWindows: ['17:00–23:30'],
      startDate: 'Sofort',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Graefestraße 22, 10967 Berlin-Kreuzberg',
    },
    responsibilities: [
      'Gäste betreuen, Speisen- und Weinempfehlungen geben',
      'Getränke- und Essensservice am Tisch',
      'Mise-en-place vor dem Abendservice',
      'Kassieren und Abrechnung',
    ],
    requirements: [
      'Erfahrung in der Gastronomie / im Service',
      'Freude an Naturweinen und unkomplizierter Gastfreundschaft',
      'Zuverlässig an geschäftigen Abenden',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'hallo@bistro-vin.de',
      deadline: null,
      contactName: 'Florian',
      instructions: 'WhatsApp an Florian oder kurz per Mail melden.',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Naturwein', 'Bistro', 'Graefekiez', 'Kreuzberg', 'Gastro'],
    evidenceNotes: ['Unabhängiges Kiez-Bistro', 'Faire Trinkgeldteilung'],
  },
  {
    id: 'ind-gastro-02',
    slug: 'barkeeper-cocktailbar-neukoelln',
    title: 'Barkeeper / Bartender (m/w/d)',
    company: 'Bar Botanica',
    district: 'Neukölln',
    postcode: '12049',
    industryId: 'gastro',
    roleFamilyId: 'bar',
    employmentForms: ['Teilzeit', 'Minijob (bis 603 €)'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Direkt vom Betrieb',
    sourceUrl: '',
    whatsapp: '+4917655029188',
    phone: '+493082910482',
    compensation: {
      label: '17,50 € / Std. + Trinkgeld',
      amountMin: 17.5,
      amountMax: 17.5,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Trinkgeld bar nach jeder Schicht',
    },
    hours: {
      label: '12–16 Std. / Woche',
      minimum: 12,
      maximum: 16,
      period: 'week',
    },
    schedule: {
      summary: '2 Schichten donnerstags bis samstags (19:00 bis ca. 02:30 Uhr)',
      workDays: ['Do', 'Fr', 'Sa'],
      timeWindows: ['19:00–02:30'],
      startDate: 'Sofort',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Schillerpromenade 34, 12049 Berlin',
    },
    responsibilities: [
      'Zubereitung klassischer und Signature Cocktails',
      'Gästekontakt an der Bar, offene Kiezatmosphäre',
      'Vorbereitung von Infusionen, Säften und Garnituren',
      'Ordnung und Sauberkeit hinter der Bar',
    ],
    requirements: [
      'Erfahrung an der Bar / Cocktailzubereitung',
      'Belastbarkeit und Humor auch bei vollem Laden',
      'Sicherer Umgang mit Kasse & Gästen',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'jobs@bar-botanica.berlin',
      deadline: null,
      contactName: 'Nico',
      instructions: 'Schreib uns kurz auf WhatsApp oder komm ab 18 Uhr direkt an der Bar vorbei.',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Bar', 'Cocktails', 'Schillerkiez', 'Neukölln', 'Nachtschicht'],
    evidenceNotes: ['Inhabergeführte Bar', 'Direkte Trinkgeldauszahlung'],
  },
  {
    id: 'ind-gastro-03',
    slug: 'kuechenhilfe-trattoria-schoeneberg',
    title: 'Küchenhilfe / Beikoch (m/w/d)',
    company: 'Trattoria da Enzo',
    district: 'Schöneberg',
    postcode: '10823',
    industryId: 'gastro',
    roleFamilyId: 'kitchen',
    employmentForms: ['Teilzeit', 'Minijob (bis 603 €)'],
    language: 'german_or_italian',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Direkt vom Betrieb',
    sourceUrl: '',
    whatsapp: '+4917633910245',
    phone: '+49307849102',
    compensation: {
      label: '15,00 € / Std. + Personalessen',
      amountMin: 15.0,
      amountMax: 15.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Tägliches frisches Essen inklusive',
    },
    hours: {
      label: '12–20 Std. / Woche',
      minimum: 12,
      maximum: 20,
      period: 'week',
    },
    schedule: {
      summary: 'Dienstag bis Samstag, Schichten 11:30–15:00 oder 17:30–22:00',
      workDays: ['Di', 'Mi', 'Do', 'Fr', 'Sa'],
      timeWindows: ['11:30–15:00', '17:30–22:00'],
      startDate: 'Ab sofort',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Akazienstraße 14, 10823 Berlin-Schöneberg',
    },
    responsibilities: [
      'Gemüse waschen, schneiden und Vorbereitungen für Pasta-Gerichte',
      'Spülbereich & Sauberkeit am Arbeitsplatz',
      'Unterstützung des Küchenchefs bei der Ausgabe',
    ],
    requirements: [
      'Zuverlässig, ordentlich und motiviert',
      'Erste Küchenerfahrung von Vorteil, aber auch Quereinsteiger willkommen',
      'Deutsch oder Italienisch',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'enzo@trattoria-enzo.de',
      deadline: null,
      contactName: 'Enzo',
      instructions: 'WhatsApp oder direkter Anruf bei Enzo unter +49307849102.',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Küche', 'Trattoria', 'Schöneberg', 'Akazienstraße', 'Pasta'],
    evidenceNotes: ['Familienbetrieb seit 15 Jahren', 'Direktkontakt'],
  },
  {
    id: 'ind-gastro-04',
    slug: 'service-ramen-bar-friedrichshain',
    title: 'Servicekraft (m/w/d) im Ramen House',
    company: 'Takumi Kiez Ramen',
    district: 'Friedrichshain',
    postcode: '10245',
    industryId: 'gastro',
    roleFamilyId: 'service',
    employmentForms: ['Werkstudent:in', 'Teilzeit'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Direkt vom Betrieb',
    sourceUrl: '',
    whatsapp: '+4917644910382',
    phone: '+493029381029',
    compensation: {
      label: '16,00 € / Std. + Trinkgeld',
      amountMin: 16.0,
      amountMax: 16.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Kostenloses Ramen-Essen nach jeder Schicht',
    },
    hours: {
      label: '16–20 Std. / Woche',
      minimum: 16,
      maximum: 20,
      period: 'week',
    },
    schedule: {
      summary: 'Wochentags & Wochenendschichten nach Dienstplan',
      workDays: ['Mo', 'Mi', 'Fr', 'Sa', 'So'],
      timeWindows: ['12:00–16:00', '17:00–22:30'],
      startDate: 'Sofort',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Boxhagener Straße 108, 10245 Berlin',
    },
    responsibilities: [
      'Bestellungen mit digitalem Kassensystem aufnehmen',
      'Servieren von frischen Ramen, Gyoza und Getränken',
      'Tische abräumen und saubere Arbeitsstationen pflegen',
    ],
    requirements: [
      'Fokus und Schnelligkeit bei lebendigem Restaurantbetrieb',
      'Gute Laune und Teamgeist',
      'Englisch fließend, Deutsch gut',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'work@kiezramen.de',
      deadline: null,
      contactName: 'Kenji',
      instructions: 'WhatsApp-Nachricht an Kenji genügt!',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Ramen', 'Service', 'Boxhagener Platz', 'Friedrichshain', 'Team'],
    evidenceNotes: ['Inhabergeführtes Restaurant', 'Faire Arbeitsbedingungen'],
  },

  // --------------------------------------------------------------------------
  // 3. KIEZ-EINZELHANDEL & BOUTIQUE
  // --------------------------------------------------------------------------
  {
    id: 'ind-retail-01',
    slug: 'buchhandlung-kiez-aushilfe-mitte',
    title: 'Aushilfe im Kiez-Buchladen (m/w/d)',
    company: 'Buchhandlung Walter & Söhne',
    district: 'Mitte',
    postcode: '10119',
    industryId: 'retail',
    roleFamilyId: 'retail',
    employmentForms: ['Minijob (bis 603 €)', 'Teilzeit'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Direkt vom Betrieb',
    sourceUrl: '',
    whatsapp: '+4917699401928',
    phone: '+49302839104',
    compensation: {
      label: '15,50 € / Std. + 30% Buchrabatt',
      amountMin: 15.5,
      amountMax: 15.5,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Mitarbeiter-Rabatt auf alle Bücher & Bildbände',
    },
    hours: {
      label: '10–15 Std. / Woche',
      minimum: 10,
      maximum: 15,
      period: 'week',
    },
    schedule: {
      summary: 'Freitags & Samstags (11:00–18:00 Uhr)',
      workDays: ['Fr', 'Sa'],
      timeWindows: ['11:00–18:00'],
      startDate: 'Sofort',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Linienstraße 132, 10119 Berlin-Mitte',
    },
    responsibilities: [
      'Kunden empfangen und bei der Buchauswahl beraten',
      'Kassieren und Geschenke einpacken',
      'Neue Buchlieferungen einbuchen und Regale kuratieren',
    ],
    requirements: [
      'Liebe zur Literatur und zum gedruckten Buch',
      'Zuverlässigkeit und Sorgfalt im Umgang mit Kunden',
      'Gute Deutsch- und Englischkenntnisse',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'post@walter-buecher.de',
      deadline: null,
      contactName: 'Christine Walter',
      instructions: 'Schreib Christine eine kurze E-Mail oder WhatsApp mit deinen Lieblingsbüchern.',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Buchhandlung', 'Kultur', 'Mitte', 'Linienstraße', 'Bücher'],
    evidenceNotes: ['Unabhängige Buchhandlung', 'Direktkontakt'],
  },
  {
    id: 'ind-retail-02',
    slug: 'vintage-mode-store-assistenz-kreuzberg',
    title: 'Store Assistant Vintage Mode & Vinyl (m/w/d)',
    company: 'Repeat Vintage & Vinyl',
    district: 'Kreuzberg',
    postcode: '10999',
    industryId: 'retail',
    roleFamilyId: 'retail',
    employmentForms: ['Werkstudent:in', 'Minijob (bis 603 €)'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Direkt vom Betrieb',
    sourceUrl: '',
    whatsapp: '+4917622910399',
    phone: '+49306129841',
    compensation: {
      label: '16,00 € / Std. + Mitarbeiterrabatt',
      amountMin: 16.0,
      amountMax: 16.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: '40% Rabatt auf Kleidung und Schallplatten',
    },
    hours: {
      label: '12–16 Std. / Woche',
      minimum: 12,
      maximum: 16,
      period: 'week',
    },
    schedule: {
      summary: '2 Schichten donnerstags bis samstags (12:00–19:30 Uhr)',
      workDays: ['Do', 'Fr', 'Sa'],
      timeWindows: ['12:00–19:30'],
      startDate: 'Nächste Woche',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Reichenberger Straße 84, 10999 Berlin',
    },
    responsibilities: [
      'Kundenbetreuung im Store, Anprobe-Organisation',
      'Kassieren und Wareneingang auszeichnen',
      'Store-Präsentation und Musik-Playlist kuratieren',
      'Kurze Fotos/Stories für den Instagram-Kanal aufnehmen',
    ],
    requirements: [
      'Affinität zu Vintage Fashion, Retro-Trends oder Musik',
      'Kommunikativ, entspannt und freundlich',
      'Fließend Englisch, Deutsch hilfreich',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'hello@repeat-vintage.berlin',
      deadline: null,
      contactName: 'David & Tara',
      instructions: 'WhatsApp-Nachricht mit kurzem Insta-Link oder zwei Sätzen.',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Vintage', 'Fashion', 'Vinyl', 'Kreuzberg', 'Store'],
    evidenceNotes: ['Unabhängige Boutique', 'Direktkontakt'],
  },
  {
    id: 'ind-retail-03',
    slug: 'unverpackt-laden-mitarbeiter-prenzlberg',
    title: 'Mitarbeiter:in für Bio-Unverpacktladen',
    company: 'KiezKorn Unverpackt',
    district: 'Prenzlauer Berg',
    postcode: '10405',
    industryId: 'retail',
    roleFamilyId: 'retail',
    employmentForms: ['Teilzeit', 'Minijob (bis 603 €)'],
    language: 'german_explicit',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Direkt vom Betrieb',
    sourceUrl: '',
    whatsapp: '+4917688391024',
    phone: '+49304439102',
    compensation: {
      label: '15,00 € / Std. + Lebensmitteleinkauf zum EK',
      amountMin: 15.0,
      amountMax: 15.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Einkauf aller Bio-Waren zum Selbstkostenpreis',
    },
    hours: {
      label: '12–15 Std. / Woche',
      minimum: 12,
      maximum: 15,
      period: 'week',
    },
    schedule: {
      summary: 'Montag & Mittwoch oder Freitag & Samstag',
      workDays: ['Mo', 'Mi', 'Fr', 'Sa'],
      timeWindows: ['10:00–16:00', '13:00–19:00'],
      startDate: 'Sofort',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Ryckestraße 21, 10405 Berlin',
    },
    responsibilities: [
      'Befüllung der Abfüllbehälter und Warenpflege',
      'Beratung von Nachbarschaftskunden',
      'Kasse bedienen und Wiegevorgänge erklären',
    ],
    requirements: [
      'Interesse an Nachhaltigkeit und Bio-Lebensmitteln',
      'Gewissenhaftigkeit und Freude am Kundenkontakt',
      'Gute Deutschkenntnisse',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'team@kiezkorn.de',
      deadline: null,
      contactName: 'Mona',
      instructions: 'WhatsApp an Mona oder einfach im Laden ansprechen.',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 320).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Bio', 'Unverpackt', 'Nachhaltigkeit', 'Prenzlauer Berg'],
    evidenceNotes: ['Inhabergeführt', 'Faire Arbeitsatmosphäre'],
  },

  // --------------------------------------------------------------------------
  // 4. HANDWERK, ATELIER & WERKSTATT
  // --------------------------------------------------------------------------
  {
    id: 'ind-craft-01',
    slug: 'fahrradmechaniker-aushilfe-friedrichshain',
    title: 'Fahrrad-Monteur & Werkstatthilfe (m/w/d)',
    company: 'VeloFix Kiez-Werkstatt',
    district: 'Friedrichshain',
    postcode: '10247',
    industryId: 'craft',
    roleFamilyId: 'mechanic',
    employmentForms: ['Teilzeit', 'Minijob (bis 603 €)'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Direkt vom Betrieb',
    sourceUrl: '',
    whatsapp: '+4917639102944',
    phone: '+49302901294',
    compensation: {
      label: '17,00 € – 19,00 € / Std.',
      amountMin: 17.0,
      amountMax: 19.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Kostenlose Nutzung der Werkstatt & Teile zum EK',
    },
    hours: {
      label: '15–25 Std. / Woche',
      minimum: 15,
      maximum: 25,
      period: 'week',
    },
    schedule: {
      summary: 'Dienstag bis Samstag flexibel einteilbar',
      workDays: ['Di', 'Mi', 'Do', 'Fr', 'Sa'],
      timeWindows: ['10:00–18:30'],
      startDate: 'Sofort',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Grünberger Straße 54, 10247 Berlin',
    },
    responsibilities: [
      'Reparaturen: Schläuche, Bremsen, Schaltungen, Reifenwechsel',
      'Fahrradannahme und kurze Schadensbegutachtung mit Kunden',
      'Aufbau neuer City- und Gravel-Bikes',
    ],
    requirements: [
      'Praktische Erfahrung im Schrauben an Fahrrädern',
      'Handwerkliches Geschick und Problemlösungskompetenz',
      'Freundliche Kommunikation mit Kundinnen und Kunden',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'werkstatt@velofix-berlin.de',
      deadline: null,
      contactName: 'Jonas',
      instructions: 'Schreib Jonas eine WhatsApp oder komm direkt mit deinem Rad in die Werkstatt.',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Fahrrad', 'Werkstatt', 'Handwerk', 'Friedrichshain', 'Bikes'],
    evidenceNotes: ['Unabhängige Kiezwerkstatt', 'Direktkontakt'],
  },
  {
    id: 'ind-craft-02',
    slug: 'keramik-studio-atelier-aushilfe-kreuzberg',
    title: 'Studio-Aushilfe im Keramikatelier (m/w/d)',
    company: 'Ton & Erde Keramikstudio',
    district: 'Kreuzberg',
    postcode: '10961',
    industryId: 'craft',
    roleFamilyId: 'studio',
    employmentForms: ['Minijob (bis 603 €)', 'Werkstudent:in'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Direkt vom Betrieb',
    sourceUrl: '',
    whatsapp: '+4917655102933',
    phone: '+49306910293',
    compensation: {
      label: '15,50 € / Std. + freie Studio-Nutzung',
      amountMin: 15.5,
      amountMax: 15.5,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Kostenlose Brennofen-Nutzung für eigene Kunstwerke',
    },
    hours: {
      label: '10–12 Std. / Woche',
      minimum: 10,
      maximum: 12,
      period: 'week',
    },
    schedule: {
      summary: '2 Nachmittage / Abende (z.B. Mi/Fr 15:00–21:00)',
      workDays: ['Mi', 'Fr', 'Sa'],
      timeWindows: ['15:00–21:00'],
      startDate: 'Ab sofort',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Bergmannstraße 102, 10961 Berlin',
    },
    responsibilities: [
      'Brennofen be- und entladen, Tonrecycling aufbereiten',
      'Studio-Ordnung halten, Glasurstationen reinigen',
      'Begrüßung von Workshop-Teilnehmer:innen',
    ],
    requirements: [
      'Sorgfältig, zuverlässig und keine Angst vor schmutzigen Händen',
      'Erste Berührungspunkte mit Töpfern / Keramik von Vorteil',
      'Gute Laune und Teamgeist',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'hallo@tonunderde.de',
      deadline: null,
      contactName: 'Clara',
      instructions: 'WhatsApp an Clara mit ein paar Sätzen zu dir.',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 270).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Keramik', 'Atelier', 'Kunst', 'Bergmannkiez', 'Töpfern'],
    evidenceNotes: ['Kreativ-Atelier', 'Freie Studiozeiten inklusive'],
  },
  {
    id: 'ind-craft-03',
    slug: 'florist-blumenladen-aushilfe-charlottenburg',
    title: 'Aushilfe im Blumenladen & Eventdekoration',
    company: 'Flora & Fauna Kiezblumen',
    district: 'Charlottenburg',
    postcode: '10629',
    industryId: 'craft',
    roleFamilyId: 'florist',
    employmentForms: ['Teilzeit', 'Minijob (bis 603 €)'],
    language: 'german_explicit',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Direkt vom Betrieb',
    sourceUrl: '',
    whatsapp: '+4917688291045',
    phone: '+49303249102',
    compensation: {
      label: '16,00 € / Std. + Blumenstrauß pro Woche',
      amountMin: 16.0,
      amountMax: 16.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Mitarbeiterrabatt & wöchentliche Blumen',
    },
    hours: {
      label: '12–16 Std. / Woche',
      minimum: 12,
      maximum: 16,
      period: 'week',
    },
    schedule: {
      summary: 'Donnerstag bis Samstag nach Absprache',
      workDays: ['Do', 'Fr', 'Sa'],
      timeWindows: ['09:00–15:00', '13:00–18:30'],
      startDate: 'Sofort',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Leonhardtstraße 12, 10629 Berlin',
    },
    responsibilities: [
      'Blumen anschneiden, wässern und Vasen pflegen',
      'Binden von Sträußen und Gestecken nach Vorlage',
      'Kundenberatung und Kassenabwicklung',
    ],
    requirements: [
      'Gespür für Farben, Formen und Naturmaterialien',
      'Pünktlich, freundlich und hilfsbereit',
      'Gute Deutschkenntnisse',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'kontakt@flora-fauna-berlin.de',
      deadline: null,
      contactName: 'Heike',
      instructions: 'WhatsApp oder direkter Anruf bei Heike.',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 350).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Floristik', 'Blumen', 'Charlottenburg', 'Kreativ', 'Deko'],
    evidenceNotes: ['Inhabergeführter Blumenladen', 'Direktkontakt'],
  },

  // --------------------------------------------------------------------------
  // 5. AUSHILFE & EVENTS
  // --------------------------------------------------------------------------
  {
    id: 'ind-event-01',
    slug: 'event-aufbau-sound-licht-kreuzberg',
    title: 'Aushilfe für Event-Aufbau & Betreuung (m/w/d)',
    company: 'KiezKultur Raum & Events',
    district: 'Kreuzberg',
    postcode: '10997',
    industryId: 'aushilfe',
    roleFamilyId: 'event',
    employmentForms: ['Kurzfristige Aushilfe', 'Minijob (bis 603 €)'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Direkt vom Betrieb',
    sourceUrl: '',
    whatsapp: '+4917644102988',
    phone: '+49306129104',
    compensation: {
      label: '17,00 € / Std. (steuerfrei im Minijob)',
      amountMin: 17.0,
      amountMax: 17.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Kostenloser Eintritt zu Konzerten & Events',
    },
    hours: {
      label: 'Flexibel auf Abruf (ca. 8–16 Std. / Eventwoche)',
      minimum: 8,
      maximum: 16,
      period: 'week',
    },
    schedule: {
      summary: 'Meistens Freitagnachmittag oder Samstagabend',
      workDays: ['Fr', 'Sa', 'So'],
      timeWindows: ['14:00–20:00', '18:00–00:00'],
      startDate: 'Laufend',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Wrangelstraße 88, 10997 Berlin',
    },
    responsibilities: [
      'Auf- und Abbau von Bestuhlung, Podesten, kleiner Lichttechnik',
      'Einlasskontrolle und Gästebetreuung',
      'Getränkeverkauf an der Eventbar',
    ],
    requirements: [
      'Körperlich fit und verlässlich',
      'Aufgeschlossenes, hilfsbereites Auftreten',
      'Deutsch oder Englisch',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'events@kiezkultur-berlin.de',
      deadline: null,
      contactName: 'Timo',
      instructions: 'WhatsApp an Timo mit kurzer Selbstvorstellung.',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 70).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Events', 'Konzert', 'Kultur', 'Wrangelkiez', 'Flexibel'],
    evidenceNotes: ['Unabhängiger Kulturverein', 'Direkte Auszahlung'],
  },
  {
    id: 'ind-event-02',
    slug: 'galerie-aufsicht-kino-neukoelln',
    title: 'Galerieaufsicht & Kassenkraft (m/w/d)',
    company: 'Kunstraum Weser48',
    district: 'Neukölln',
    postcode: '12045',
    industryId: 'aushilfe',
    roleFamilyId: 'culture',
    employmentForms: ['Minijob (bis 603 €)', 'Werkstudent:in'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Direkt vom Betrieb',
    sourceUrl: '',
    whatsapp: '+4917622019488',
    phone: '+49306291049',
    compensation: {
      label: '15,00 € / Std.',
      amountMin: 15.0,
      amountMax: 15.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Ruhige Schichten mit Zeit zum Lernen zwischen Besuchern',
    },
    hours: {
      label: '8–12 Std. / Woche',
      minimum: 8,
      maximum: 12,
      period: 'week',
    },
    schedule: {
      summary: 'Samstag & Sonntag (13:00–19:00 Uhr)',
      workDays: ['Sa', 'So'],
      timeWindows: ['13:00–19:00'],
      startDate: 'Sofort',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Weserstraße 48, 12045 Berlin',
    },
    responsibilities: [
      'Empfang der Galeriebesucher und Ausgabe von Katalogen',
      'Aufsicht in den Ausstellungsräumen',
      'Öffnen und Schließen der Räumlichkeiten',
    ],
    requirements: [
      'Zuverlässig, pünktlich und kunstinteressiert',
      'Gute Deutsch- oder Englischkenntnisse',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'hallo@weser48.berlin',
      deadline: null,
      contactName: 'Mira',
      instructions: 'E-Mail oder WhatsApp mit 2 Zeilen an Mira.',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 190).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Galerie', 'Kunst', 'Neukölln', 'Wochenende', 'Ruhig'],
    evidenceNotes: ['Freier Projektraum', 'Direktkontakt'],
  },

  // --------------------------------------------------------------------------
  // 6. PRIVAT & COMMUNITY (Babysitting, Nachhilfe, Umzugshilfe)
  // --------------------------------------------------------------------------
  {
    id: 'ind-privat-01',
    slug: 'kinderbetreuung-abholen-kita-prenzlauer-berg',
    title: 'Herzliche Kinderbetreuung für 2 Kinder (4 & 7 Jahre)',
    company: 'Familie Lindner (Privat)',
    district: 'Prenzlauer Berg',
    postcode: '10437',
    industryId: 'privat',
    roleFamilyId: 'care',
    employmentForms: ['Minijob (bis 603 €)', 'Privater Aushilfsjob'],
    language: 'german_explicit',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Private:r Anbieter:in',
    sourceUrl: '',
    whatsapp: '+4917631902844',
    phone: '+4917631902844',
    compensation: {
      label: '18,00 € / Std. bar oder Überweisung',
      amountMin: 18.0,
      amountMax: 18.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'weekly',
      grossNet: 'net',
      extras: 'Feste wöchentliche Bezahlung, langfristig gesucht',
    },
    hours: {
      label: '6–8 Std. / Woche',
      minimum: 6,
      maximum: 8,
      period: 'week',
    },
    schedule: {
      summary: 'Dienstag & Donnerstag von 15:30 bis 18:30 Uhr',
      workDays: ['Di', 'Do'],
      timeWindows: ['15:30–18:30'],
      startDate: 'Ab nächster Woche',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Stargarder Straße, 10437 Berlin',
    },
    responsibilities: [
      'Kinder von Kita & Schule in der Nähe abholen',
      'Spielplatzbesuch oder Spiele zu Hause',
      'Kleinen Nachmittagssnack vorbereiten',
    ],
    requirements: [
      'Erfahrung in der Kinderbetreuung und liebevoller Umgang',
      'Verlässlichkeit ist uns besonders wichtig',
      'Fließend Deutsch',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'lindner.berlin@posteo.de',
      deadline: null,
      contactName: 'Katharina Lindner',
      instructions: 'Gern direkt per WhatsApp schreiben oder kurz anrufen.',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Kinderbetreuung', 'Babysitter', 'Prenzlauer Berg', 'Familie', 'Privat'],
    evidenceNotes: ['100% Privater Inserent', 'Direktkontakt Familie'],
  },
  {
    id: 'ind-privat-02',
    slug: 'nachhilfe-mathematik-englisch-gymnasium-mitte',
    title: 'Nachhilfe Mathematik & Englisch (Klasse 8–10)',
    company: 'Familie Özdemir (Privat)',
    district: 'Mitte',
    postcode: '10178',
    industryId: 'privat',
    roleFamilyId: 'tutor',
    employmentForms: ['Privater Aushilfsjob', 'Werkstudent:in'],
    language: 'german_explicit',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Private:r Anbieter:in',
    sourceUrl: '',
    whatsapp: '+4917699018477',
    phone: '+4917699018477',
    compensation: {
      label: '22,00 € / Std. bar',
      amountMin: 22.0,
      amountMax: 22.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'weekly',
      grossNet: 'net',
      extras: 'Direkte Barzahlung nach jeder Einheit',
    },
    hours: {
      label: '3–4 Std. / Woche (2x 90 Min.)',
      minimum: 3,
      maximum: 4,
      period: 'week',
    },
    schedule: {
      summary: 'Nachmittags nach der Schule (z.B. Montag & Mittwoch 16:30–18:00)',
      workDays: ['Mo', 'Mi'],
      timeWindows: ['16:30–18:00'],
      startDate: 'Sofort',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Nähe Alexanderplatz, 10178 Berlin',
    },
    responsibilities: [
      'Geduldiges Erklären von Mathematikthemen (Lineare Funktionen, Geometrie)',
      'Grammatik- & Vokabeltraining Englisch',
      'Vorbereitung auf Klassenarbeiten',
    ],
    requirements: [
      'Gute Mathe- und Englischkenntnisse (z.B. Student:in)',
      'Geduldige und motivierende Art',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'oezdemir.nachhilfe@web.de',
      deadline: null,
      contactName: 'Murat Özdemir',
      instructions: 'Schreib uns kurz auf WhatsApp.',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 130).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Nachhilfe', 'Mathematik', 'Englisch', 'Studentenjob', 'Mitte'],
    evidenceNotes: ['Privater Inserent', 'Guter Stundenlohn (22 €)'],
  },
  {
    id: 'ind-privat-03',
    slug: 'umzugshelfer-wochenende-kreuzberg',
    title: '2x Kräftige Umzugshelfer für Samstag gesucht',
    company: 'Julian M. (Privat)',
    district: 'Kreuzberg',
    postcode: '10961',
    industryId: 'privat',
    roleFamilyId: 'helper',
    employmentForms: ['Kurzfristige Aushilfe'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Private:r Anbieter:in',
    sourceUrl: '',
    whatsapp: '+4917655829104',
    phone: '+4917655829104',
    compensation: {
      label: '20,00 € / Std. bar + Pizza & Getränke',
      amountMin: 20.0,
      amountMax: 20.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'after_shift',
      grossNet: 'net',
      extras: 'Garantiert 5 Stunden bezahlt (mind. 100 € bar auf die Hand)',
    },
    hours: {
      label: '5–6 Stunden einmalig',
      minimum: 5,
      maximum: 6,
      period: 'shift',
    },
    schedule: {
      summary: 'Kommenden Samstag von 09:30 bis ca. 15:00 Uhr',
      workDays: ['Sa'],
      timeWindows: ['09:30–15:00'],
      startDate: 'Kommender Samstag',
      endDate: 'Kommender Samstag',
    },
    workplace: {
      type: 'on_site',
      address: 'Gneisenaustraße (2. OG ohne Fahrstuhl) nach Reichenberger Str. (EG)',
    },
    responsibilities: [
      'Kisten und Möbel tragen (Bett, Tisch, Sofa, Waschmaschine)',
      'Transporter beladen und sichern',
    ],
    requirements: [
      'Körperlich fit, pünktlich und zuverlässig',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'julian.umzug.berlin@gmail.com',
      deadline: null,
      contactName: 'Julian',
      instructions: 'WhatsApp an Julian mit Name & Bestätigung für Samstag!',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Umzug', 'Helfer', 'Barzahlung', 'Sofort', 'Kreuzberg'],
    evidenceNotes: ['Privat', 'Barzahlung sofort nach der Schicht'],
  },
  {
    id: 'ind-privat-04',
    slug: 'hundebetreuung-gassi-tempelhof',
    title: 'Liebevolle Hunde-Gassigänger:in für Golden Retriever',
    company: 'Sabine & Hund Charlie (Privat)',
    district: 'Tempelhof',
    postcode: '12101',
    industryId: 'privat',
    roleFamilyId: 'care',
    employmentForms: ['Privater Aushilfsjob', 'Minijob (bis 603 €)'],
    language: 'german_explicit',
    listingOrigin: 'employer_posted',
    isIndependentLister: true,
    isUserListing: true,
    sourceKind: 'direct_employer',
    sourceName: 'Private:r Anbieter:in',
    sourceUrl: '',
    whatsapp: '+4917644991033',
    phone: '+4917644991033',
    compensation: {
      label: '16,00 € pro 60 Min. Spaziergang',
      amountMin: 16.0,
      amountMax: 16.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'weekly',
      grossNet: 'net',
      extras: 'Wöchentliche Auszahlung nach Wunsch',
    },
    hours: {
      label: '3–4 Mal pro Woche (ca. 4 Std.)',
      minimum: 3,
      maximum: 4,
      period: 'week',
    },
    schedule: {
      summary: 'Montag, Mittwoch, Freitag mittags (12:30–13:30 Uhr)',
      workDays: ['Mo', 'Mi', 'Fr'],
      timeWindows: ['12:30–13:30'],
      startDate: 'Ab sofort',
      endDate: null,
    },
    workplace: {
      type: 'on_site',
      address: 'Nähe Tempelhofer Feld, 12101 Berlin',
    },
    responsibilities: [
      'Gemeinsamer Spaziergang über das Tempelhofer Feld',
      'Ballspielen und Wasser geben',
    ],
    requirements: [
      'Erfahrung mit Hunden und tierlieb',
      'Zuverlässigkeit bei Wind und Wetter',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'sabine.charlie.berlin@web.de',
      deadline: null,
      contactName: 'Sabine',
      instructions: 'Schreib Sabine gern auf WhatsApp für ein erstes Kennenlernen.',
    },
    firstSeenAt: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    sourceVerifiedAt: new Date().toISOString(),
    tags: ['Hunde', 'Gassi', 'Tempelhofer Feld', 'Tierbetreuung', 'Privat'],
    evidenceNotes: ['100% Privat', 'Direkter Kontakt'],
  },
  // Additional neighborhood employers to reach 50+ diverse listings
  ...generateAdditionalNeighborhoodListings(),
];

function generateAdditionalNeighborhoodListings(): PreviewJob[] {
  const KIEZ_SPOTS = [
    { name: 'Kiez-Späti & Deli 36', district: 'Kreuzberg', cat: 'retail', role: 'Späti-Verkäufer:in', wage: '15,50 € / Std.', hours: '12–20h', tel: '+49306120991' },
    { name: 'Café Morgenstern', district: 'Schöneberg', cat: 'cafe', role: 'Barista & Küchenhilfe', wage: '16,00 € / Std.', hours: '15h', tel: '+49307829101' },
    { name: 'Kino Kiezlichtspiele', district: 'Neukölln', cat: 'aushilfe', role: 'Kassen- & Einlasskraft', wage: '15,00 € / Std.', hours: '10–15h', tel: '+49306281022' },
    { name: 'Plattenladen Groove Record', district: 'Friedrichshain', cat: 'retail', role: 'Aushilfe Schallplattenverkauf', wage: '15,50 € / Std.', hours: '12h', tel: '+49302910294' },
    { name: 'Räucherei & Fischbistro Spree', district: 'Treptow', cat: 'gastro', role: 'Service & Theke', wage: '16,50 € / Std.', hours: '15–20h', tel: '+49305360192' },
    { name: 'Kerzenmanufaktur Berlin', district: 'Wedding', cat: 'craft', role: 'Produktionshilfe & Verpackung', wage: '15,00 € / Std.', hours: '10–20h', tel: '+49304610291' },
    { name: 'Kaffeerösterei Kiezbohne', district: 'Mitte', cat: 'cafe', role: 'Barista (Siebträger)', wage: '17,00 € / Std.', hours: '20h', tel: '+49302810923' },
    { name: 'Bio-Eisdiele Kiezschlecker', district: 'Prenzlauer Berg', cat: 'cafe', role: 'Eisverkäufer:in (m/w/d)', wage: '15,50 € / Std.', hours: '10–18h', tel: '+49304410294' },
    { name: 'Siebdruck-Atelier Kollektiv', district: 'Kreuzberg', cat: 'craft', role: 'Druckhilfe & Werkstattleitung', wage: '17,00 € / Std.', hours: '15h', tel: '+49306190281' },
    { name: 'Familie Brandt (Privat)', district: 'Steglitz', cat: 'privat', role: 'Gartenhilfe & Rasenmähen', wage: '18,00 € / Std.', hours: '4–6h/Woche', tel: '+491763910284' },
    { name: 'Pâtisserie Petit Paris', district: 'Charlottenburg', cat: 'cafe', role: 'Verkauf französische Törtchen', wage: '16,00 € / Std.', hours: '15–20h', tel: '+49303120194' },
    { name: 'Kiez-Pizzeria Forno', district: 'Moabit', cat: 'gastro', role: 'Pizzabäcker-Gehilfe / Küchenhilfe', wage: '16,00 € / Std.', hours: '16h', tel: '+49303910291' },
    { name: 'Design-Papeterie & Buch', district: 'Mitte', cat: 'retail', role: 'Store-Mitarbeiter:in', wage: '15,50 € / Std.', hours: '12–15h', tel: '+49302830192' },
    { name: 'Dr. Bergmann (Privat)', district: 'Pankow', cat: 'privat', role: 'Seniorenbegleitung & Spaziergänge', wage: '19,00 € / Std.', hours: '6h/Woche', tel: '+491768820192' },
    { name: 'Tapas-Bar La Esquina', district: 'Friedrichshain', cat: 'gastro', role: 'Tresenkraft / Tapasservice', wage: '16,50 € / Std.', hours: '12–16h', tel: '+49302940192' },
    { name: 'Boutique Green Fashion', district: 'Kreuzberg', cat: 'retail', role: 'Kundenberatung & Kasse', wage: '15,50 € / Std.', hours: '14h', tel: '+49306129188' },
    { name: 'Yoga & Pilates Kiezstudio', district: 'Prenzlauer Berg', cat: 'aushilfe', role: 'Studio-Check-In & Rezeption', wage: '15,00 € / Std.', hours: '10–12h', tel: '+49304401928' },
    { name: 'Fahrradmanufaktur Stahlrad', district: 'Neukölln', cat: 'craft', role: 'Fahrrad-Monteur:in', wage: '18,00 € / Std.', hours: '20h', tel: '+49306271928' },
    { name: 'Craftbeer-Bar Hopfenkiez', district: 'Friedrichshain', cat: 'gastro', role: 'Barkeeper:in Taproom', wage: '17,00 € / Std.', hours: '12–18h', tel: '+49302901928' },
    // Berlin Spots
    { city: 'Berlin', name: 'Familie Krause (Privat)', district: 'Charlottenburg', cat: 'privat', role: 'Babysitter am Wochenende', wage: '17,50 € / Std.', hours: '5–8h', tel: '+491765501928' },
    { city: 'Berlin', name: 'Bio-Käse Kieztheke', district: 'Schöneberg', cat: 'retail', role: 'Verkauf & Verkostung', wage: '16,00 € / Std.', hours: '12–15h', tel: '+49307810291' },
    { city: 'Berlin', name: 'Keramikwerkstatt Kiezton', district: 'Wedding', cat: 'craft', role: 'Werkstattassistenz', wage: '15,50 € / Std.', hours: '10h', tel: '+49304620192' },
    { city: 'Berlin', name: 'Kiez-Café Sonnendeck', district: 'Lichtenberg', cat: 'cafe', role: 'Service & Barista', wage: '15,50 € / Std.', hours: '15h', tel: '+49305510291' },
    { city: 'Berlin', name: 'Indie Record Store 33rpm', district: 'Kreuzberg', cat: 'retail', role: 'Verkauf & Plattensortierung', wage: '15,00 € / Std.', hours: '10–12h', tel: '+49306120491' },
    { city: 'Berlin', name: 'Familie Nguyen (Privat)', district: 'Lichtenberg', cat: 'privat', role: 'Deutsch-Nachhilfe Grundschule', wage: '20,00 € / Std.', hours: '4h/Woche', tel: '+491764401928' },
    { city: 'Berlin', name: 'Teehaus Matcha & Kräuter', district: 'Mitte', cat: 'cafe', role: 'Tee-Sommelier & Verkauf', wage: '16,50 € / Std.', hours: '15–20h', tel: '+49302820194' },
    { city: 'Berlin', name: 'Blumenatelier Wilde Wiese', district: 'Neukölln', cat: 'craft', role: 'Floristik-Aushilfe', wage: '16,00 € / Std.', hours: '12h', tel: '+49306280192' },
    { city: 'Berlin', name: 'Kiezbistro Pasta e Basta', district: 'Prenzlauer Berg', cat: 'gastro', role: 'Service & Runner', wage: '16,00 € / Std.', hours: '14–18h', tel: '+49304420194' },
    { city: 'Berlin', name: 'Marktstand Bio-Obst', district: 'Kreuzberg', cat: 'retail', role: 'Wochenmarkt-Verkäufer:in (Sa)', wage: '17,00 € / Std.', hours: '8h', tel: '+491763301928' },
    { city: 'Berlin', name: 'Kulturzentrum Alte Halle', district: 'Wedding', cat: 'aushilfe', role: 'Garderobe & Einlass', wage: '15,00 € / Std.', hours: '8–12h', tel: '+49304690192' },
    { city: 'Berlin', name: 'Indie Publisher & Magazin', district: 'Mitte', cat: 'retail', role: 'Versand- & Packhilfe', wage: '15,00 € / Std.', hours: '10h', tel: '+49302890192' },
    { city: 'Berlin', name: 'Holzwerkstatt Möbelkiez', district: 'Friedrichshain', cat: 'craft', role: 'Schreinergehilfe / Schleifen', wage: '18,00 € / Std.', hours: '15–20h', tel: '+49302980192' },
    { city: 'Berlin', name: 'Café Glückskind', district: 'Schöneberg', cat: 'cafe', role: 'Kuchenbäcker:in & Theke', wage: '16,00 € / Std.', hours: '12–16h', tel: '+49307890192' },
    { city: 'Berlin', name: 'Weinhandlung Kiezrebe', district: 'Charlottenburg', cat: 'retail', role: 'Kundenberatung Wein', wage: '16,50 € / Std.', hours: '12h', tel: '+49303190192' },
    { city: 'Berlin', name: 'Fotostudio Kiezlicht', district: 'Kreuzberg', cat: 'craft', role: 'Studio-Assistent:in', wage: '16,00 € / Std.', hours: '10–15h', tel: '+49306190492' },
    { city: 'Berlin', name: 'Familie Sommer (Privat)', district: 'Pankow', cat: 'privat', role: 'Hausaufgabenbetreuung (6. Klasse)', wage: '20,00 € / Std.', hours: '4h', tel: '+491768890192' },
    { city: 'Berlin', name: 'Burger-Küche Handcrafted', district: 'Neukölln', cat: 'gastro', role: 'Grillmeister:in & Burgerbau', wage: '16,50 € / Std.', hours: '15–20h', tel: '+49306290192' },
    { city: 'Berlin', name: 'Secondhand Kiezschrank', district: 'Friedrichshain', cat: 'retail', role: 'Sortierung & Verkauf', wage: '15,00 € / Std.', hours: '12h', tel: '+49302990192' },
    { city: 'Berlin', name: 'Eiswerkstatt Vanille & Co.', district: 'Mitte', cat: 'cafe', role: 'Eisportionierer:in', wage: '15,50 € / Std.', hours: '10–15h', tel: '+49302890492' },
    { city: 'Berlin', name: 'Musikstudio Beatkiez', district: 'Kreuzberg', cat: 'aushilfe', role: 'Studio-Empfang & Assistenz', wage: '16,00 € / Std.', hours: '10h', tel: '+49306180192' },

    // Hamburg Spots
    { city: 'Hamburg', name: 'Schanzen-Rösterei Elbe', district: 'Sternschanze', cat: 'cafe', role: 'Specialty Barista & Latte Art', wage: '16,50 € / Std.', hours: '15–20h', tel: '+49404319012' },
    { city: 'Hamburg', name: 'Hafenbistro St. Pauli', district: 'St. Pauli', cat: 'gastro', role: 'Servicekraft & Theke', wage: '16,00 € / Std.', hours: '12–18h', tel: '+49403190412' },
    { city: 'Hamburg', name: 'Altona Craft Buchhandlung', district: 'Altona', cat: 'retail', role: 'Buchberater:in & Kasse', wage: '15,50 € / Std.', hours: '12h', tel: '+49403890122' },
    { city: 'Hamburg', name: 'Eimsbütteler Holzmanufaktur', district: 'Eimsbüttel', cat: 'craft', role: 'Möbelrestaurierung Aushilfe', wage: '17,50 € / Std.', hours: '15h', tel: '+49404990122' },
    { city: 'Hamburg', name: 'Familie Jansen (Privat)', district: 'Winterhude', cat: 'privat', role: 'Mathe-Nachhilfe Gymnasium', wage: '22,00 € / Std.', hours: '4h', tel: '+491764129012' },
    { city: 'Hamburg', name: 'Boutique Hafenstil', district: 'HafenCity', cat: 'retail', role: 'Modeberatung & Store Assistenz', wage: '16,00 € / Std.', hours: '10–15h', tel: '+49403690122' },

    // München Spots
    { city: 'München', name: 'Glockenbach Specialty Coffee', district: 'Glockenbachviertel', cat: 'cafe', role: 'Barista & Café Allrounder', wage: '17,00 € / Std.', hours: '15–20h', tel: '+49892019012' },
    { city: 'München', name: 'Schwabinger Feinkost & Wein', district: 'Schwabing', cat: 'retail', role: 'Verkauf Feinkosttheke', wage: '17,50 € / Std.', hours: '12–16h', tel: '+49893319012' },
    { city: 'München', name: 'Maxvorstadt Galerie & Café', district: 'Maxvorstadt', cat: 'aushilfe', role: 'Ausstellungsassistenz & Kasse', wage: '16,00 € / Std.', hours: '10h', tel: '+49892819012' },
    { city: 'München', name: 'Familie Weber (Privat)', district: 'Haidhausen', cat: 'privat', role: 'Kinderbetreuung (3 & 6 Jahre)', wage: '20,00 € / Std.', hours: '6h', tel: '+491765129012' },
    { city: 'München', name: 'Trattoria del Kiez', district: 'Sendling', cat: 'gastro', role: 'Küchenhilfe & Vorbereitung', wage: '16,50 € / Std.', hours: '15h', tel: '+49897619012' },

    // Köln Spots
    { city: 'Köln', name: 'Ehrenfeld Rösterei & Bar', district: 'Ehrenfeld', cat: 'cafe', role: 'Barista & Frühstücksservice', wage: '16,00 € / Std.', hours: '15–20h', tel: '+49221519012' },
    { city: 'Köln', name: 'Belgisches Viertel Vintage Store', district: 'Belgisches Viertel', cat: 'retail', role: 'Store Assistant & Styling', wage: '15,50 € / Std.', hours: '12h', tel: '+49221251901' },
    { city: 'Köln', name: 'Südstadt Tapas & Wein', district: 'Südstadt', cat: 'gastro', role: 'Abendservice & Runner', wage: '16,00 € / Std.', hours: '12–16h', tel: '+49221311901' },
    { city: 'Köln', name: 'Kölner Keramik Atelier', district: 'Nippes', cat: 'craft', role: 'Kursassistenz & Brennofenbetreuung', wage: '17,00 € / Std.', hours: '10h', tel: '+49221731901' },

    // Frankfurt am Main Spots
    { city: 'Frankfurt am Main', name: 'Bornheim Kaffeemanufaktur', district: 'Bornheim', cat: 'cafe', role: 'Head Barista & Service', wage: '16,50 € / Std.', hours: '15–20h', tel: '+49694519012' },
    { city: 'Frankfurt am Main', name: 'Sachsenhausen Apfelwein & Bistro', district: 'Sachsenhausen', cat: 'gastro', role: 'Servicekraft Kiezterrasse', wage: '16,00 € / Std.', hours: '12–18h', tel: '+49696119012' },
    { city: 'Frankfurt am Main', name: 'Nordend Bio-Bäckerei', district: 'Nordend', cat: 'retail', role: 'Frühschicht Verkauf', wage: '16,50 € / Std.', hours: '12h', tel: '+49695519012' },

    // Leipzig Spots
    { city: 'Leipzig', name: 'Plagwitzer Kultur-Späti & Café', district: 'Plagwitz', cat: 'cafe', role: 'Tresenkraft & Barista', wage: '15,00 € / Std.', hours: '15h', tel: '+493414819012' },
    { city: 'Leipzig', name: 'Connewitz Druckwerkstatt', district: 'Connewitz', cat: 'craft', role: 'Siebdruck-Aushilfe', wage: '15,50 € / Std.', hours: '10–15h', tel: '+493413019012' },
    { city: 'Leipzig', name: 'Südvorstadt Bio-Boutique', district: 'Südvorstadt', cat: 'retail', role: 'Kundenberatung & Kasse', wage: '15,00 € / Std.', hours: '12h', tel: '+493413919012' },

    // Düsseldorf Spots
    { city: 'Düsseldorf', name: 'Carlsplatz Marktcafé', district: 'Altstadt', cat: 'cafe', role: 'Barista & Marktverkauf', wage: '16,50 € / Std.', hours: '15–20h', tel: '+49211329012' },
    { city: 'Düsseldorf', name: 'Little Tokyo Ramen & Matcha', district: 'Stadtmitte', cat: 'gastro', role: 'Service & Küchenassistenz', wage: '16,00 € / Std.', hours: '12–16h', tel: '+49211369012' },
    { city: 'Düsseldorf', name: 'Flingern Design & Interior', district: 'Flingern', cat: 'retail', role: 'Store-Mitarbeiter:in', wage: '15,50 € / Std.', hours: '12h', tel: '+49211689012' },

    // Stuttgart Spots
    { city: 'Stuttgart', name: 'Kessel-Kaffee Manufaktur', district: 'Stuttgart-Mitte', cat: 'cafe', role: 'Barista & Kaffeerösterei', wage: '17,00 € / Std.', hours: '15–20h', tel: '+49711229012' },
    { city: 'Stuttgart', name: 'Feinkost & Weinstube Bohnenviertel', district: 'Bohnenviertel', cat: 'gastro', role: 'Abendservice & Weinausschank', wage: '16,50 € / Std.', hours: '12–16h', tel: '+49711239012' },
    { city: 'Stuttgart', name: 'Stuttgart-West Biobäcker', district: 'Stuttgart-West', cat: 'retail', role: 'Verkauf Kiezbäckerei', wage: '16,00 € / Std.', hours: '10–14h', tel: '+49711619012' },

    // Dortmund Spots
    { city: 'Dortmund', name: 'Kreuzviertel Rösterei', district: 'Kreuzviertel', cat: 'cafe', role: 'Specialty Barista & Theke', wage: '15,50 € / Std.', hours: '15–20h', tel: '+49231129012' },
    { city: 'Dortmund', name: 'Kaiserviertel Feinkost', district: 'Kaiserviertel', cat: 'retail', role: 'Verkauf & Kundenberatung', wage: '15,00 € / Std.', hours: '12h', tel: '+49231519012' },
    { city: 'Dortmund', name: 'Bierkultur & Kiezbrauhaus', district: 'Innenstadt', cat: 'gastro', role: 'Zapfer & Schankkellner:in', wage: '16,00 € / Std.', hours: '12–18h', tel: '+49231509012' },

    // Essen Spots
    { city: 'Essen', name: 'Rüttenscheider Café & Deli', district: 'Rüttenscheid', cat: 'cafe', role: 'Service & Barista', wage: '15,50 € / Std.', hours: '15–20h', tel: '+49201779012' },
    { city: 'Essen', name: 'Kupferdreh Hofladen', district: 'Kupferdreh', cat: 'retail', role: 'Verkauf & Obsthof', wage: '15,00 € / Std.', hours: '10–15h', tel: '+49201489012' },
    { city: 'Essen', name: 'Zollverein Event-Support', district: 'Stoppenberg', cat: 'aushilfe', role: 'Einlassbetreuung & Guide', wage: '16,00 € / Std.', hours: '8–16h', tel: '+49201839012' },

    // Bremen Spots
    { city: 'Bremen', name: 'Viertel Kaffeebar', district: 'Ostertor', cat: 'cafe', role: 'Barista & Tagesschichten', wage: '15,50 € / Std.', hours: '15–20h', tel: '+49421719012' },
    { city: 'Bremen', name: 'Schnoor Kunsthandwerk', district: 'Schnoor', cat: 'craft', role: 'Werkstattverkauf & Kunst', wage: '15,00 € / Std.', hours: '12h', tel: '+49421329012' },
    { city: 'Bremen', name: 'Weserlust Biergarten', district: 'Überseestadt', cat: 'gastro', role: 'Servicekraft & Runner', wage: '16,00 € / Std.', hours: '12–16h', tel: '+49421389012' },

    // Dresden Spots
    { city: 'Dresden', name: 'Neustadt Kaffeerösterei', district: 'Äußere Neustadt', cat: 'cafe', role: 'Barista & Kaffeetheke', wage: '15,00 € / Std.', hours: '15–20h', tel: '+49351809012' },
    { city: 'Dresden', name: 'Altstadt Galerie & Shop', district: 'Innere Altstadt', cat: 'retail', role: 'Kassen- & Storehilfe', wage: '15,00 € / Std.', hours: '12h', tel: '+49351499012' },
    { city: 'Dresden', name: 'Elbufer Lounge & Bistro', district: 'Blasewitz', cat: 'gastro', role: 'Terrassenservice', wage: '15,50 € / Std.', hours: '12–16h', tel: '+49351319012' },

    // Hannover Spots
    { city: 'Hannover', name: 'Linden Kiezrösterei', district: 'Linden', cat: 'cafe', role: 'Specialty Coffee Barista', wage: '15,50 € / Std.', hours: '15–20h', tel: '+49511459012' },
    { city: 'Hannover', name: 'List Buch & Papeterie', district: 'List', cat: 'retail', role: 'Kundenberatung & Kasse', wage: '15,00 € / Std.', hours: '12h', tel: '+49511669012' },
    { city: 'Hannover', name: 'Maschsee Strandbistro', district: 'Südstadt', cat: 'gastro', role: 'Thekenkraft & Service', wage: '16,00 € / Std.', hours: '14–18h', tel: '+49511809012' },

    // Nürnberg Spots
    { city: 'Nürnberg', name: 'Gostenhof Specialty Coffee', district: 'Gostenhof', cat: 'cafe', role: 'Barista & Frühstücksservice', wage: '16,00 € / Std.', hours: '15–20h', tel: '+49911269012' },
    { city: 'Nürnberg', name: 'Burgviertel Handwerksatelier', district: 'Altstadt, St. Sebald', cat: 'craft', role: 'Atelierassistenz & Verkauf', wage: '16,00 € / Std.', hours: '10–14h', tel: '+49911229012' },
    { city: 'Nürnberg', name: 'Kaiserburg Weinstube', district: 'St. Lorenz', cat: 'gastro', role: 'Abendservice & Schankdienst', wage: '16,50 € / Std.', hours: '12–16h', tel: '+49911249012' },
  ];

  return KIEZ_SPOTS.map((spot, i) => {
    const cityName = (spot as any).city || 'Berlin';
    const slug = `${spot.role.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${spot.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${spot.district.toLowerCase()}-${cityName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;
    const wageNum = parseFloat(spot.wage.replace(',', '.'));
    const isPrivate = spot.cat === 'privat';

    return {
      id: `ind-gen-${i + 1}`,
      slug,
      title: `${spot.role} (m/w/d)`,
      company: spot.name,
      city: cityName,
      district: spot.district,
      postcode: '10' + (100 + i * 15).toString().slice(0, 3),
      industryId: spot.cat,
      roleFamilyId: spot.cat,
      employmentForms: [isPrivate ? 'Privater Aushilfsjob' : 'Minijob (bis 603 €)', 'Teilzeit'],
      language: 'german_and_english',
      listingOrigin: 'employer_posted',
      isIndependentLister: true,
      isUserListing: true,
      sourceKind: 'direct_employer',
      sourceName: isPrivate ? 'Private:r Anbieter:in' : 'Direkt vom Betrieb',
      sourceUrl: '',
      whatsapp: '+49' + (1700000000 + i * 98711),
      phone: spot.tel,
      compensation: {
        label: `${spot.wage} ${isPrivate ? 'bar' : '+ Extras'}`,
        amountMin: wageNum,
        amountMax: wageNum,
        currency: 'EUR',
        rateInterval: 'hour',
        payoutCadence: isPrivate ? 'after_shift' : 'monthly',
        grossNet: isPrivate ? 'net' : 'gross',
        extras: isPrivate ? 'Direkte Auszahlung' : 'Mitarbeitervergünstigung',
      },
      hours: {
        label: `${spot.hours} / Woche`,
        minimum: 10,
        maximum: 20,
        period: 'week',
      },
      schedule: {
        summary: 'Flexible Absprache im Team',
        workDays: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
        timeWindows: ['10:00–16:00', '14:00–20:00'],
        startDate: 'Sofort',
        endDate: null,
      },
      workplace: {
        type: 'on_site',
        address: `${spot.district}, ${cityName}`,
      },
      responsibilities: [
        `Verlässliche Mitarbeit bei ${spot.name}`,
        'Eigenständiges, sorgfältiges Arbeiten',
        'Freundlicher Umgang mit Kundinnen & Nachbarn im Kiez',
      ],
      requirements: [
        'Freundlich, pünktlich und motiviert',
        'Zuverlässig im Kiez-Team',
      ],
      application: {
        method: 'email',
        url: null,
        email: `hallo@${spot.name.toLowerCase().replace(/[^a-z0-9]+/g, '')}.${cityName === 'Berlin' ? 'berlin' : 'de'}`,
        deadline: null,
        contactName: isPrivate ? 'Familienkontakt' : 'Inhaber:in',
        instructions: 'Schreib uns kurz auf WhatsApp oder ruf direkt an. Kein Lebenslauf nötig!',
      },
      firstSeenAt: new Date(Date.now() - (i + 1) * 3600000 * 3).toISOString(),
      sourceVerifiedAt: new Date().toISOString(),
      tags: [cityName, spot.district, spot.role.split(' ')[0], 'Unabhängig', 'Direktkontakt'],
      evidenceNotes: ['100% Unabhängiger Betrieb', 'Keine Agentur', 'Direkte Einstellung'],
    };
  });
}
