import type { HousingListing } from './housing-types';

export const previewHousingListings: HousingListing[] = [
  {
    id: 'housing-fshain-wg-boxi',
    title: 'Sonniges WG-Zimmer am Boxhagener Kiez mit Balkon',
    listingType: 'wg_room',
    district: 'Friedrichshain',
    postcode: '10245',
    neighborhood: 'Boxhagener Kiez',
    streetAddress: 'Gärtnerstraße',
    latitude: 52.5065,
    longitude: 13.4589,
    kaltmieteEur: 460,
    nebenkostenEur: 120,
    warmmieteEur: 580,
    kautionEur: 1380,
    roomSqm: 22,
    totalRooms: 3,
    floorLevel: 3,
    furnished: 'fully',
    anmeldungPossible: true,
    subletAuthorized: true,
    contractType: 'fixed_term',
    moveInDate: '2026-10-01',
    moveOutDate: '2027-03-31',
    minStayMonths: 6,
    energyClass: 'C',
    heatingSource: 'Fernwärme',
    buildingYear: 1910,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'Da ich für ein Semester nach Barcelona gehe, vermiete ich mein helles, ruhiges 22m² Zimmer im beliebten Boxhagener Kiez unter. Voll möbliert mit großem Bett (160x200), Schreibtisch, Kleiderschrank und Balkonzugang. Die WG teilen wir zu dritt (2 berufstätige Masterstudenten an der HU/TU). Gemütliche Wohnküche mit Spülmaschine und Waschmaschine. Anmeldung (Wohnungsgeberbestätigung) ist offiziell vom Vermieter genehmigt und selbstverständlich möglich!',
    contactMethod: 'email',
    contactEmail: 'fshain-wg-sublet@jobroofs.com',
    contactName: 'Lukas & Sarah',
    contactPhone: null,
    publicationState: 'published',
    firstSeenAt: '2026-09-02T10:00:00Z',
    expiresAt: '2026-10-02T10:00:00Z',
    isDemo: true,
  },
  {
    id: 'housing-xberg-studio-wrangel',
    title: 'Ruhiges 1-Zimmer Studio im Wrangelkiez (Gartenhaus)',
    listingType: 'sublet',
    district: 'Kreuzberg',
    postcode: '10997',
    neighborhood: 'Wrangelkiez',
    streetAddress: 'Wrangelstraße',
    latitude: 52.4998,
    longitude: 13.4412,
    kaltmieteEur: 710,
    nebenkostenEur: 180,
    warmmieteEur: 890,
    kautionEur: 1500,
    roomSqm: 38,
    totalRooms: 1,
    floorLevel: 2,
    furnished: 'fully',
    anmeldungPossible: true,
    subletAuthorized: true,
    contractType: 'fixed_term',
    moveInDate: '2026-10-15',
    moveOutDate: '2027-02-28',
    minStayMonths: 4,
    energyClass: 'D',
    heatingSource: 'Erdgas',
    buildingYear: 1905,
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'Charmante 1-Zimmer Altbauwohnung im ruhigen 2. Hinterhof. Komplett ausgestattet mit Dielenboden, Einbauküche, Duschbad und Highspeed-WLAN. Ideal für Austauschstudierende, Praktikanten oder Übergangsphasen. Nur 3 Minuten zum Schlesischen Tor (U1/U3) und Görlitzer Park. Anmeldung möglich, offizielle Genehmigung der Hausverwaltung liegt vor.',
    contactMethod: 'email',
    contactEmail: 'wrangel-studio@jobroofs.com',
    contactName: 'Elena V.',
    contactPhone: null,
    publicationState: 'published',
    firstSeenAt: '2026-09-02T14:00:00Z',
    expiresAt: '2026-10-02T14:00:00Z',
    isDemo: true,
  },
  {
    id: 'housing-neukoelln-reuterkiez',
    title: 'Helles Zimmer im lebendigen Reuterkiez nahe Maybachufer',
    listingType: 'wg_room',
    district: 'Neukölln',
    postcode: '12047',
    neighborhood: 'Reuterkiez',
    streetAddress: 'Weserstraße',
    latitude: 52.4912,
    longitude: 13.4312,
    kaltmieteEur: 420,
    nebenkostenEur: 100,
    warmmieteEur: 520,
    kautionEur: 1260,
    roomSqm: 18,
    totalRooms: 2,
    floorLevel: 4,
    furnished: 'fully',
    anmeldungPossible: true,
    subletAuthorized: true,
    contractType: 'fixed_term',
    moveInDate: '2026-10-01',
    moveOutDate: '2027-04-30',
    minStayMonths: 6,
    energyClass: 'C',
    heatingSource: 'Fernwärme',
    buildingYear: 1920,
    images: [
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'Biete schönes 18m² Zimmer mit hohen Decken und großem Fenster zum Innenhof. 2 Minuten zu Fuß zum Maybachufer-Wochenmarkt und U8 Schönleinstraße. Dein Mitbewohner Jonas (27) arbeitet im Grafikbereich. Entspannte Atmosphäre, offizielle Untermiete mit Anmeldung.',
    contactMethod: 'email',
    contactEmail: 'reuterkiez-room@jobroofs.com',
    contactName: 'Jonas M.',
    contactPhone: null,
    publicationState: 'published',
    firstSeenAt: '2026-09-01T16:00:00Z',
    expiresAt: '2026-10-01T16:00:00Z',
    isDemo: true,
  },
  {
    id: 'housing-mitte-torstrasse-nachmieter',
    title: 'Nachmieter gesucht: Helle 2-Zimmer Altbauwohnung nahe Rosenthaler Platz',
    listingType: 'nachmieter',
    district: 'Mitte',
    postcode: '10119',
    neighborhood: 'Rosenthaler Vorstadt',
    streetAddress: 'Torstraße',
    latitude: 52.5303,
    longitude: 13.4038,
    kaltmieteEur: 980,
    nebenkostenEur: 270,
    warmmieteEur: 1250,
    kautionEur: 2940,
    roomSqm: 64,
    totalRooms: 2,
    floorLevel: 2,
    furnished: 'unfurnished',
    anmeldungPossible: true,
    subletAuthorized: true,
    contractType: 'open_ended',
    moveInDate: '2026-11-01',
    moveOutDate: null,
    minStayMonths: 12,
    energyClass: 'B',
    heatingSource: 'Fernwärme',
    buildingYear: 1900,
    images: [
      'https://images.unsplash.com/photo-1502005229762-ee152da7c5d6?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1540518614846-7ede433c4b13?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'Wir ziehen berufsbedingt um und schlagen unserer Hausverwaltung solvente Nachmieter für diese wunderschöne 64m² Wohnung vor. Stuckdecken, Flügeltüren, frisch abgeschliffene Dielen, Balkon und moderne Einbauküche (Abstand für EBK und Regale: 800€ VB). Unbefristeter Hauptmietvertrag direkt mit der Hausverwaltung. Erforderliche Unterlagen: SCHUFA, 3 Gehaltsnachweise / Bürgschaft, Mietschuldenfreiheitsbescheinigung.',
    contactMethod: 'email',
    contactEmail: 'torstrasse-nachmieter@jobroofs.com',
    contactName: 'Maximilian & Clara',
    contactPhone: null,
    publicationState: 'published',
    firstSeenAt: '2026-09-02T18:00:00Z',
    expiresAt: '2026-10-02T18:00:00Z',
    isDemo: true,
  },
  {
    id: 'housing-pberg-helmholtzkiez',
    title: 'Sonnige 1.5-Zimmer Wohnung zur Zwischenmiete am Helmholtzplatz',
    listingType: 'sublet',
    district: 'Pankow',
    postcode: '10437',
    neighborhood: 'Helmholtzkiez',
    streetAddress: 'Lychener Straße',
    latitude: 52.5472,
    longitude: 13.4142,
    kaltmieteEur: 620,
    nebenkostenEur: 170,
    warmmieteEur: 790,
    kautionEur: 1200,
    roomSqm: 45,
    totalRooms: 1.5,
    floorLevel: 1,
    furnished: 'fully',
    anmeldungPossible: true,
    subletAuthorized: true,
    contractType: 'fixed_term',
    moveInDate: '2026-10-01',
    moveOutDate: '2027-01-31',
    minStayMonths: 4,
    energyClass: 'C',
    heatingSource: 'Erdgas',
    buildingYear: 1908,
    images: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'Sehr gepflegte, komplett eingerichtete Altbauwohnung am lebendigen Helmholtzplatz. Separater Schlafraum, offene Wohnküche, Bad mit Badewanne. Waschmaschine, Geschirrspüler und 250 Mbit Internet vorhanden. Offiziell angemeldete Zwischenmiete mit Wohnungsgeberbestätigung.',
    contactMethod: 'email',
    contactEmail: 'helmholtz-sublet@jobroofs.com',
    contactName: 'Felix B.',
    contactPhone: null,
    publicationState: 'published',
    firstSeenAt: '2026-09-03T09:00:00Z',
    expiresAt: '2026-10-03T09:00:00Z',
    isDemo: true,
  },
  {
    id: 'housing-wedding-sprengelkiez-student',
    title: 'Studenten-WG: Großes Zimmer nahe TU & Charité Campus Virchow',
    listingType: 'wg_room',
    district: 'Mitte',
    postcode: '13353',
    neighborhood: 'Sprengelkiez / Wedding',
    streetAddress: 'Torfstraße',
    latitude: 52.5418,
    longitude: 13.3582,
    kaltmieteEur: 360,
    nebenkostenEur: 110,
    warmmieteEur: 470,
    kautionEur: 800,
    roomSqm: 20,
    totalRooms: 3,
    floorLevel: 3,
    furnished: 'partially',
    anmeldungPossible: true,
    subletAuthorized: true,
    contractType: 'fixed_term',
    moveInDate: '2026-10-01',
    moveOutDate: '2027-09-30',
    minStayMonths: 12,
    energyClass: 'D',
    heatingSource: 'Fernwärme',
    buildingYear: 1960,
    images: [
      'https://images.unsplash.com/photo-1540518614846-7ede433c4b13?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'Super angebundene 3er-WG am Sprengelkiez (U9 Amrumer Str. / U6 Leopoldplatz). 5 Min zum Charité Campus Virchow, 15 Min zur TU Berlin. Das Zimmer ist 20m² groß, teilmöbliert (Bettgestell, Schrank, Schreibtisch können übernommen werden). Wir suchen eine/n entspannte/n Mitbewohner/in. Anmeldung möglich!',
    contactMethod: 'email',
    contactEmail: 'sprengel-wg@jobroofs.com',
    contactName: 'Tim & Maya',
    contactPhone: null,
    publicationState: 'published',
    firstSeenAt: '2026-09-03T11:00:00Z',
    expiresAt: '2026-10-03T11:00:00Z',
    isDemo: true,
  },
  {
    id: 'housing-schoeneberg-exchange',
    title: 'Wohnungstausch: Biete ruhige 2-Zimmer-Wohnung am Akazienkiez gegen 3-Zimmer',
    listingType: 'exchange',
    district: 'Tempelhof-Schöneberg',
    postcode: '10823',
    neighborhood: 'Akazienkiez',
    streetAddress: 'Belziger Straße',
    latitude: 52.4872,
    longitude: 13.3571,
    kaltmieteEur: 590,
    nebenkostenEur: 160,
    warmmieteEur: 750,
    kautionEur: 1770,
    roomSqm: 56,
    totalRooms: 2,
    floorLevel: 2,
    furnished: 'unfurnished',
    anmeldungPossible: true,
    subletAuthorized: true,
    contractType: 'open_ended',
    moveInDate: '2026-11-01',
    moveOutDate: null,
    minStayMonths: null,
    energyClass: 'C',
    heatingSource: 'Erdgas',
    buildingYear: 1912,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'Wohnungstausch (städtische Wohnungsbaugesellschaft / Gewobag): Biete wunderschöne, sonnige 2-Zimmer-Altbauwohnung (56m², Dielen, Südbalkon) am beliebten Akazienkiez für 750€ warm. Wir suchen wegen Familienzuwachs mindestens 3 Zimmer (ab 75m²) in Schöneberg, Kreuzberg, Neukölln oder Friedrichshain bis 1.400€ warm. Beide Vermieter müssen dem Tausch zustimmen.',
    contactMethod: 'email',
    contactEmail: 'akazien-tausch@jobroofs.com',
    contactName: 'Nora & David',
    contactPhone: null,
    publicationState: 'published',
    firstSeenAt: '2026-09-03T12:00:00Z',
    expiresAt: '2026-10-03T12:00:00Z',
    isDemo: true,
  },
];
