import type { PreviewJob } from './types';

export const previewJobs: PreviewJob[] = [
  {
    id: 'job-boxi-service-xberg',
    slug: 'servicekraft-bar-aushilfe-kreuzberg',
    title: 'Servicekraft & Bar-Aushilfe (m/w/d)',
    company: 'Café Boxi Berlin',
    district: 'Kreuzberg',
    postcode: '10997',
    industryId: 'gastronomy',
    roleFamilyId: 'service',
    employmentForms: ['Minijob', 'Teilzeit'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    compensation: {
      label: '15,50 € / Stunde + Trinkgeld',
      amountMin: 15.5,
      amountMax: 15.5,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Trinkgeld-Pool fair nach Schichten aufgeteilt',
    },
    hours: {
      label: '12–18 Std. / Woche',
      minimum: 12,
      maximum: 18,
      period: 'week',
    },
    schedule: {
      summary: '2 bis 3 Schichten wählbar (Do–So)',
      workDays: ['Donnerstag', 'Freitag', 'Samstag', 'Sonntag'],
      timeWindows: ['16:00–23:00'],
      startDate: 'Ab sofort',
      endDate: null,
    },
    workplace: { type: 'on_site', address: 'Wrangelstraße, 10997 Berlin-Kreuzberg' },
    responsibilities: [
      'Herzlicher Empfang unserer Kiez-Gäste und Bestellungsaufnahme',
      'Servieren von frischen Drinks, Snacks und Kaffeespezialitäten',
      'Vorbereitung der Bar-Stationen und Pflege eines einladenden Gastbereichs',
    ],
    requirements: [
      'Gute Deutsch- oder Englischkenntnisse für den Gästeaustausch',
      'Zuverlässigkeit und Freude an lebendiger Kiez-Gastronomie',
      'Erste Gastronomieerfahrung wünschenswert, Quereinsteiger willkommen',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'boxi-jobs@jobroofs.com',
      deadline: 'Offen bis Besetzung',
      contactName: 'Team Café Boxi',
      instructions: 'Schicke uns gerne eine kurze Nachricht mit deinen Wunsch-Schichten.',
    },
    firstSeenAt: '2026-09-03T08:00:00Z',
    sourceVerifiedAt: '2026-09-05T10:00:00Z',
    sourceKind: 'direct_employer',
    sourceName: 'Café Boxi Berlin',
    sourceUrl: 'https://jobroofs.com/jobs/servicekraft-bar-aushilfe-kreuzberg',
    tags: ['Barista', 'Service', 'Kreuzberg', 'Trinkgeld', 'Flexible Schichten'],
    summary: 'Lebendiges Kiez-Café im Wrangelkiez sucht herzliche Service-Unterstützung mit fairem Trinkgeld-Pool.',
    evidenceNotes: ['Verifizierter Berliner Arbeitgeber', 'Direkte Bewerbung ohne Zwischenhändler'],
  },
  {
    id: 'job-wrangel-barista',
    slug: 'barista-specialty-coffee-wrangelkiez',
    title: 'Barista & Coffee Allrounder (m/w/d)',
    company: 'Wrangel Roasters Berlin',
    district: 'Kreuzberg',
    postcode: '10997',
    industryId: 'gastronomy',
    roleFamilyId: 'barista',
    employmentForms: ['Werkstudent', 'Teilzeit'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    compensation: {
      label: '16,50 € / Stunde',
      amountMin: 16.5,
      amountMax: 16.5,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Mitarbeiter-Kaffee & Barista-Fortbildungen inklusive',
    },
    hours: {
      label: '15–20 Std. / Woche',
      minimum: 15,
      maximum: 20,
      period: 'week',
    },
    schedule: {
      summary: 'Frühschichten (07:30–14:30) oder Nachmittagsschichten',
      workDays: ['Montag', 'Dienstag', 'Donnerstag', 'Samstag'],
      timeWindows: ['07:30–14:30', '13:30–19:00'],
      startDate: 'Zum nächsten Monat',
      endDate: null,
    },
    workplace: { type: 'on_site', address: 'Falckensteinstraße, 10997 Berlin' },
    responsibilities: [
      'Zubereitung von Espresso- und Filterkaffees auf La Marzocco Siebträgermaschinen',
      'Beratung von Kaffeeliebhabern zu Röstprofilen und Bohnenherkunft',
      'Mahlgrad-Justierung und sensorische Qualitätskontrolle',
    ],
    requirements: [
      'Leidenschaft für Specialty Coffee und grundlegendes Verständnis für Dial-in & Latte Art',
      'Teamfähige Arbeitsweise und strukturierter Ablauf bei Stoßzeiten',
      'Sichere Kommunikation auf Deutsch oder Englisch',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'roasters@jobroofs.com',
      deadline: 'Laufend',
      contactName: 'Felix (Head Barista)',
      instructions: 'Kurzes Anschreiben mit deinen Vorkenntnissen an uns senden.',
    },
    firstSeenAt: '2026-09-02T11:00:00Z',
    sourceVerifiedAt: '2026-09-05T09:30:00Z',
    sourceKind: 'direct_employer',
    sourceName: 'Wrangel Roasters Berlin',
    sourceUrl: 'https://jobroofs.com/jobs/barista-specialty-coffee-wrangelkiez',
    tags: ['Specialty Coffee', 'La Marzocco', 'Latte Art', 'Werkstudent'],
    summary: 'Spezialitätenrösterei in Kreuzberg vergibt Barista-Schichten an Kaffeebegeisterte mit Vorliebe für Spitzenkaffee.',
    evidenceNotes: ['Direktkontakt zum Röstmeister', 'Feste Schichtplanung 2 Wochen im Voraus'],
  },
  {
    id: 'job-mitte-pizza-prep',
    slug: 'kuechenhilfe-pizza-prep-mitte',
    title: 'Küchenhilfe & Pizza Prep (m/w/d)',
    company: 'Pizzeria Napoletana Mitte',
    district: 'Mitte',
    postcode: '10115',
    industryId: 'gastronomy',
    roleFamilyId: 'kitchen',
    employmentForms: ['Minijob', 'Kurzfristig'],
    language: 'german_or_english',
    listingOrigin: 'employer_posted',
    compensation: {
      label: '15,00 € / Stunde + Personalessen',
      amountMin: 15.0,
      amountMax: 15.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Frische Holzofenpizza & Getränke pro Schicht frei',
    },
    hours: {
      label: '10–15 Std. / Woche',
      minimum: 10,
      maximum: 15,
      period: 'week',
    },
    schedule: {
      summary: 'Abendschichten ab 17:30 Uhr (Mi–So)',
      workDays: ['Mittwoch', 'Freitag', 'Sonntag'],
      timeWindows: ['17:30–22:30'],
      startDate: 'Sofortiger Einstieg möglich',
      endDate: null,
    },
    workplace: { type: 'on_site', address: 'Torstraße, 10115 Berlin-Mitte' },
    responsibilities: [
      'Vorbereitung frischer Zutaten (Fior di Latte, San Marzano Tomaten, Basilikum)',
      'Unterstützung der Pizzaioli bei Stoßzeiten am Belegposten',
      'Bedienung der Spülstraße und Einhaltung von HACCP-Hygienestandards',
    ],
    requirements: [
      'Zuverlässigkeit, Pünktlichkeit und zupackende Haltung',
      'Bereitschaft zur Arbeit im lebhaften Küchenumfeld',
      'Rote Karte (Belehrung nach Infektionsschutzgesetz) oder Bereitschaft zur Beantragung',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'mitte-pizza@jobroofs.com',
      deadline: 'Bis Ende des Monats',
      contactName: 'Gianni (Küchenchef)',
      instructions: 'Schreibe uns kurz oder komme direkt ab 16:30 Uhr auf der Torstraße vorbei.',
    },
    firstSeenAt: '2026-09-01T14:20:00Z',
    sourceVerifiedAt: '2026-09-04T16:00:00Z',
    sourceKind: 'direct_employer',
    sourceName: 'Pizzeria Napoletana Mitte',
    sourceUrl: 'https://jobroofs.com/jobs/kuechenhilfe-pizza-prep-mitte',
    tags: ['Küche', 'Pizza Napoletana', 'Personalessen', 'Mitte', 'Abendschicht'],
    summary: 'Authentische neapolitanische Holzofenpizzeria auf der Torstraße sucht Verstärkung am Vorbereitungsposten.',
    evidenceNotes: ['Verifizierte Restaurantführung', 'Überstunden minutengenau vergütet'],
  },
  {
    id: 'job-neukoelln-kiez-kino',
    slug: 'kino-service-theke-neukoelln',
    title: 'Kino-Service & Bar-Crew (m/w/d)',
    company: 'Kiez-Kino & Kulturbar Neukölln',
    district: 'Neukölln',
    postcode: '12047',
    industryId: 'culture',
    roleFamilyId: 'service',
    employmentForms: ['Minijob', 'Teilzeit'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    compensation: {
      label: '14,80 € / Stunde',
      amountMin: 14.8,
      amountMax: 14.8,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Kostenloser Eintritt zu allen Filmvorführungen & Festivals',
    },
    hours: {
      label: '10–16 Std. / Woche',
      minimum: 10,
      maximum: 16,
      period: 'week',
    },
    schedule: {
      summary: '2 bis 3 Abend- oder Spätschichten',
      workDays: ['Dienstag', 'Freitag', 'Samstag'],
      timeWindows: ['17:00–23:30', '19:30–01:00'],
      startDate: 'Ab Mitte des Monats',
      endDate: null,
    },
    workplace: { type: 'on_site', address: 'Weserstraße, 12047 Berlin' },
    responsibilities: [
      'Ticketverkauf und Einlassbetreuung unserer Kinogäste',
      'Getränke- und Snack-Ausgabe an der Kinobar (Bio-Popcorn, Craft Beer, Limos)',
      'Saal-Check vor und nach den Vorführungen',
    ],
    requirements: [
      'Freundliches und souveränes Auftreten im Kulturbetrieb',
      'Affinität zu Arthouse-Kino, Dokumentarfilmen und Kiez-Kultur',
      'Zuverlässigkeit bei Spätschichten am Wochenende',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'kino@jobroofs.com',
      deadline: 'Laufend',
      contactName: 'Theaterleitung Neukölln',
      instructions: 'Kurze Vorstellung und Lieblingsfilm per E-Mail mitsenden.',
    },
    firstSeenAt: '2026-09-02T16:00:00Z',
    sourceVerifiedAt: '2026-09-05T08:00:00Z',
    sourceKind: 'direct_employer',
    sourceName: 'Kiez-Kino & Kulturbar Neukölln',
    sourceUrl: 'https://jobroofs.com/jobs/kino-service-theke-neukoelln',
    tags: ['Kino', 'Kultur', 'Neukölln', 'Freikarten', 'Abendjob'],
    summary: 'Unabhängiges Programmkino im Reuterkiez sucht filmbegeisterte Teammitglieder für Bar und Einlass.',
    evidenceNotes: ['Feste Kiez-Institution seit 2012', 'Entspanntes studentisches Team'],
  },
  {
    id: 'job-pberg-kollwitz-brunch',
    slug: 'brunch-service-host-prenzlauer-berg',
    title: 'Brunch Service & Guest Host (m/w/d)',
    company: 'Kollwitz Brunch & Café',
    district: 'Pankow',
    postcode: '10405',
    industryId: 'gastronomy',
    roleFamilyId: 'service',
    employmentForms: ['Minijob', 'Werkstudent'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    compensation: {
      label: '15,80 € / Stunde + gutes Trinkgeld',
      amountMin: 15.8,
      amountMax: 15.8,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Hoher Trinkgeldschnitt an Wochenenden',
    },
    hours: {
      label: '12–16 Std. / Woche',
      minimum: 12,
      maximum: 16,
      period: 'week',
    },
    schedule: {
      summary: 'Tagsüber am Wochenende (keine Nachtschichten)',
      workDays: ['Samstag', 'Sonntag'],
      timeWindows: ['09:00–16:30'],
      startDate: 'Ab sofort',
      endDate: null,
    },
    workplace: { type: 'on_site', address: 'Kollwitzstraße, 10405 Berlin' },
    responsibilities: [
      'Gästeplatzierung und Aufrechterhaltung eines entspannten Ablaufs beim Wochenendbrunch',
      'Servieren von Spezialitäten-Tellern, Kaffees und frischen Säften',
      'Kassieren mit modernem iPad POS-System',
    ],
    requirements: [
      'Zuverlässige Verfügbarkeit samstags und sonntags',
      'Schnelle Auffassungsgabe und herzliche Ausstrahlung auch bei vollem Haus',
      'Fließend Deutsch oder Englisch',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'kollwitz@jobroofs.com',
      deadline: 'Schnellstmöglich',
      contactName: 'Marlene (Café-Leitung)',
      instructions: 'Sende deinen Lebenslauf oder eine kurze Übersicht deiner bisherigen Jobs.',
    },
    firstSeenAt: '2026-09-03T12:00:00Z',
    sourceVerifiedAt: '2026-09-05T07:15:00Z',
    sourceKind: 'direct_employer',
    sourceName: 'Kollwitz Brunch & Café',
    sourceUrl: 'https://jobroofs.com/jobs/brunch-service-host-prenzlauer-berg',
    tags: ['Brunch', 'Wochenende', 'Prenzlauer Berg', 'Tagesschicht', 'Trinkgeld'],
    summary: 'Beliebtes Café am Kollwitzplatz sucht zuverlässige Wochenend-Verstärkung für erstklassigen Brunch-Service.',
    evidenceNotes: ['Feste Tagesschichten ohne Spätarbeit', 'Sehr gute Trinkgeldbedingungen'],
  },
  {
    id: 'job-fshain-raw-events',
    slug: 'event-crew-buehnenhilfe-raw-areal',
    title: 'Event Crew & Bühnenhilfe (m/w/d)',
    company: 'RAW Stage Productions Berlin',
    district: 'Friedrichshain',
    postcode: '10245',
    industryId: 'events',
    roleFamilyId: 'logistics',
    employmentForms: ['Kurzfristig', 'Aushilfe'],
    language: 'german_or_english',
    listingOrigin: 'employer_posted',
    compensation: {
      label: '19,00 € / Stunde',
      amountMin: 19.0,
      amountMax: 19.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Nacht- und Wochenendzuschläge',
    },
    hours: {
      label: 'Tagesjobs / Events (flexibel)',
      minimum: 8,
      maximum: 24,
      period: 'week',
    },
    schedule: {
      summary: 'Projekteinsätze nach Eventkalender (Fr–So)',
      workDays: ['Freitag', 'Samstag', 'Sonntag'],
      timeWindows: ['14:00–22:00', '22:00–06:00'],
      startDate: 'Laufende Konzert- und Festival-Saison',
      endDate: null,
    },
    workplace: { type: 'on_site', address: 'Revaler Straße (RAW-Gelände), 10245 Berlin' },
    responsibilities: [
      'Auf- und Abbau von Ton-, Licht- und Bühnenelementen für Konzerte und Messen',
      'Backstage-Logistik und Equipment-Transport in Zusammenarbeit mit den Tour-Crews',
      'Unterstützung bei Absperrungen und Materialbereitstellung',
    ],
    requirements: [
      'Hohe Zuverlässigkeit, körperliche Fitness und Teamgeist',
      'Sicherheitsschuhe (S3) erforderlich',
      'Keine speziellen Vorkenntnisse nötig — gründliche Sicherheitseinweisung vor Ort',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'crew@jobroofs.com',
      deadline: 'Laufender Pool-Aufbau',
      contactName: 'Einsatzleitung Events',
      instructions: 'Melde dich an für den Berliner Event-Pool mit deiner Rufnummer.',
    },
    firstSeenAt: '2026-09-04T09:00:00Z',
    sourceVerifiedAt: '2026-09-05T11:00:00Z',
    sourceKind: 'direct_employer',
    sourceName: 'RAW Stage Productions Berlin',
    sourceUrl: 'https://jobroofs.com/jobs/event-crew-buehnenhilfe-raw-areal',
    tags: ['Events', 'Konzerte', 'RAW Areal', 'Festival', 'Zuschläge', '19€/h'],
    summary: 'Produktionscrew für Open-Air Shows und Clubnächte auf dem RAW Gelände in Friedrichshain.',
    evidenceNotes: ['Überdurchschnittliche 19€/h Vergütung', 'Direkte Abrechnung nach jedem Projekteinsatz'],
  },
  {
    id: 'job-mitte-greenride-courier',
    slug: 'fahrradkurier-e-cargo-mitte',
    title: 'Fahrradkurier / E-Cargo Fahrer (m/w/d)',
    company: 'GreenRide Logistics Berlin',
    district: 'Mitte',
    postcode: '10119',
    industryId: 'logistics',
    roleFamilyId: 'courier',
    employmentForms: ['Minijob', 'Teilzeit', 'Werkstudent'],
    language: 'german_or_english',
    listingOrigin: 'employer_posted',
    compensation: {
      label: '17,00 € / Stunde + Lieferbonus',
      amountMin: 17.0,
      amountMax: 17.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Neuestes Riese & Müller E-Cargobike & wetterfeste Kleidung gestellt',
    },
    hours: {
      label: '10–25 Std. / Woche',
      minimum: 10,
      maximum: 25,
      period: 'week',
    },
    schedule: {
      summary: 'Schichten flexibel per App wählbar',
      workDays: ['Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag'],
      timeWindows: ['08:30–13:30', '13:30–18:30'],
      startDate: 'Sofort startklar',
      endDate: null,
    },
    workplace: { type: 'on_site', address: 'Rosenthaler Platz, 10119 Berlin' },
    responsibilities: [
      'Emissionsfreie Zustellung von Dokumenten, Kiez-Waren und Medikamenten in Innenstadtbezirken',
      'Sichere Bedienung des firmeneigenen E-Lastenrads',
      'Dokumentation der Übergaben über moderne Kurier-App',
    ],
    requirements: [
      'Sicherer Fahrstil im Berliner Straßenverkehr',
      'Eigenes Smartphone mit Datenvolumen für Navigation',
      'Zuverlässigkeit und wetterfeste Motivation',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'ride@jobroofs.com',
      deadline: 'Laufend',
      contactName: 'Operations Berlin',
      instructions: 'Kurze Nachricht genügt. Probefahrt findet am Rosenthaler Platz statt.',
    },
    firstSeenAt: '2026-09-03T15:00:00Z',
    sourceVerifiedAt: '2026-09-05T08:30:00Z',
    sourceKind: 'direct_employer',
    sourceName: 'GreenRide Logistics Berlin',
    sourceUrl: 'https://jobroofs.com/jobs/fahrradkurier-e-cargo-mitte',
    tags: ['E-Bike', 'Kurier', 'Nachhaltig', 'Mitte', 'Flexible Schichten'],
    summary: 'Nachhaltiger Berliner Kurierdienst sucht umweltbewusste Fahrer für moderne E-Lastenräder.',
    evidenceNotes: ['Fahrzeug und Versicherung komplett vom Arbeitgeber gestellt', 'Pünktliche Monatsauszahlung'],
  },
  {
    id: 'job-schoeneberg-concept-store',
    slug: 'store-assistant-kiez-deli-schoeneberg',
    title: 'Store Assistant & Counter Service (m/w/d)',
    company: 'Späti & Deli Concept Store',
    district: 'Tempelhof-Schöneberg',
    postcode: '10777',
    industryId: 'retail',
    roleFamilyId: 'retail',
    employmentForms: ['Minijob', 'Teilzeit'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    compensation: {
      label: '15,20 € / Stunde',
      amountMin: 15.2,
      amountMax: 15.2,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: '20% Mitarbeiterrabatt auf das gesamte Sortiment',
    },
    hours: {
      label: '12–20 Std. / Woche',
      minimum: 12,
      maximum: 20,
      period: 'week',
    },
    schedule: {
      summary: 'Nachmittags- und Vorabendschichten',
      workDays: ['Dienstag', 'Mittwoch', 'Freitag', 'Samstag'],
      timeWindows: ['14:00–20:30'],
      startDate: 'Ab sofort',
      endDate: null,
    },
    workplace: { type: 'on_site', address: 'Winterfeldtstraße, 10777 Berlin' },
    responsibilities: [
      'Kundenberatung zu lokalen Berliner Produkten, Weinen und Bio-Spezialitäten',
      'Kassiertätigkeit und Auffüllen der Regale und Frischetheke',
      'Zubereitung von kleinen Snacks und Kaffees to-go',
    ],
    requirements: [
      'Freundliche, offene Art und Freude am Kundenkontakt im Kiez',
      'Gepflegtes Erscheinungsbild und Sorgfalt bei der Kassenführung',
      'Gute Deutsch- oder Englischkenntnisse',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'deli@jobroofs.com',
      deadline: 'Laufend',
      contactName: 'Store Management',
      instructions: 'Sende uns deinen Lebenslauf per E-Mail oder sprich uns direkt im Laden an.',
    },
    firstSeenAt: '2026-09-02T13:45:00Z',
    sourceVerifiedAt: '2026-09-04T18:00:00Z',
    sourceKind: 'direct_employer',
    sourceName: 'Späti & Deli Concept Store',
    sourceUrl: 'https://jobroofs.com/jobs/store-assistant-kiez-deli-schoeneberg',
    tags: ['Einzelhandel', 'Deli', 'Schöneberg', 'Mitarbeiterrabatt', 'Kiez'],
    summary: 'Moderner Feinkost- und Kiez-Laden am Winterfeldtplatz sucht sympathische Unterstützung für Kasse und Verkauf.',
    evidenceNotes: ['Fester Dienstplan', 'Zentrale Lage mit U-Bahn Anbindung U1/U2/U3/U4'],
  },
];

export const previewSources = [
  {
    name: 'Independent hospitality employers',
    kind: 'Direct employers',
    niches: 'Gastronomy, Hotels',
    cadence: '12h',
    state: 'Adapter queue',
    reason: 'High job turnover; fragmented supply',
  },
  {
    name: 'Berlin venues and event operators',
    kind: 'Direct employers',
    niches: 'Events, Culture, Nightlife',
    cadence: '6h',
    state: 'Adapter queue',
    reason: 'Immediate listings require faster checks',
  },
  {
    name: 'Local retail career pages',
    kind: 'Direct employers',
    niches: 'Retail, Food retail',
    cadence: '24h',
    state: 'Discovery queue',
    reason: 'Many employers never reach large boards',
  },
  {
    name: 'Specialist flexible-work boards',
    kind: 'Specialist boards',
    niches: 'Cross-niche',
    cadence: '24h',
    state: 'Policy review',
    reason: 'Secondary coverage and reconciliation',
  },
  {
    name: 'Large general job boards',
    kind: 'Large boards',
    niches: 'Cross-niche',
    cadence: '48h',
    state: 'Secondary only',
    reason: 'Coverage check, not differentiation',
  },
] as const;

