import type { PreviewJob } from './types';

export const previewJobs: PreviewJob[] = [
  {
    id: 'preview-1',
    slug: 'sample-cafe-service-kreuzberg',
    title: 'Service Aushilfe',
    company: 'Example neighbourhood café',
    district: 'Kreuzberg',
    postcode: '10997',
    industryId: 'gastronomy',
    roleFamilyId: 'service',
    employmentForms: ['Minijob'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    compensation: {
      label: '€14.20 / hour',
      amountMin: 14.2,
      amountMax: 14.2,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Tips shared by shift',
    },
    hours: {
      label: '10–15 hours / week',
      minimum: 10,
      maximum: 15,
      period: 'week',
    },
    schedule: {
      summary: 'Two or three shifts per week',
      workDays: ['Friday', 'Saturday', 'Sunday'],
      timeWindows: ['16:00–23:00'],
      startDate: 'As soon as possible',
      endDate: null,
    },
    workplace: { type: 'on_site', address: '10997 Berlin-Kreuzberg' },
    responsibilities: [
      'Welcome guests and take orders',
      'Serve food and drinks',
      'Prepare tables and keep the service area tidy',
    ],
    requirements: [
      'German and English for guest communication',
      'Reliable weekend availability',
      'Hospitality experience helpful but not required',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'jobs@example.test',
      deadline: '30 September 2026',
      contactName: 'Example hiring team',
      instructions: 'Send a short introduction and your usual availability.',
    },
    firstSeenAt: '2026-09-01T07:20:00Z',
    sourceVerifiedAt: '2026-09-01T07:24:00Z',
    sourceKind: 'direct_employer',
    sourceName: 'Posted on JOBROOFS by employer',
    sourceUrl: '#',
    tags: ['Weekend', 'English explicitly accepted', 'Pay stated'],
    summary: 'Join a small café team for evening and weekend service shifts.',
    evidenceNotes: [
      'Employer supplied the job details',
      'Application email requires employer verification',
      'Pay, hours and schedule supplied as structured fields',
    ],
    isDemo: true,
  },
  {
    id: 'preview-2',
    slug: 'sample-event-crew-tempelhof',
    title: 'Event crew',
    company: 'Example Berlin venue',
    district: 'Tempelhof',
    postcode: '12101',
    industryId: 'events',
    roleFamilyId: 'event-crew',
    employmentForms: ['Short-term employment'],
    language: 'not_stated',
    listingOrigin: 'employer_posted',
    compensation: {
      label: '€120 / shift',
      amountMin: 120,
      amountMax: 120,
      currency: 'EUR',
      rateInterval: 'shift',
      payoutCadence: 'weekly',
      grossNet: 'gross',
      extras: 'Meal during long shifts',
    },
    hours: {
      label: '6–10 hours / shift',
      minimum: 6,
      maximum: 10,
      period: 'shift',
    },
    schedule: {
      summary: 'Choose individual event shifts',
      workDays: ['Thursday', 'Friday', 'Saturday', 'Sunday'],
      timeWindows: ['Afternoon', 'Evening', 'Late night'],
      startDate: 'September 2026',
      endDate: 'December 2026',
    },
    workplace: { type: 'on_site', address: '12101 Berlin-Tempelhof' },
    responsibilities: [
      'Set up event spaces',
      'Guest direction and admission support',
      'Reset the venue after events',
    ],
    requirements: [
      'Comfortable standing for long periods',
      'Available for at least two shifts per month',
    ],
    application: {
      method: 'external_link',
      url: '#',
      email: null,
      deadline: null,
      contactName: null,
      instructions:
        'Complete the employer application form and select your availability.',
    },
    firstSeenAt: '2026-09-01T06:10:00Z',
    sourceVerifiedAt: '2026-09-01T06:15:00Z',
    sourceKind: 'direct_employer',
    sourceName: 'Posted on JOBROOFS by employer',
    sourceUrl: '#',
    tags: ['Evening', 'Weekend', 'Shift choice'],
    summary: 'Flexible event shifts for setup, guest support and venue reset.',
    evidenceNotes: [
      'Employer supplied the listing',
      'External application URL pending verification',
      'No language requirement supplied',
    ],
    isDemo: true,
  },
  {
    id: 'preview-3',
    slug: 'sample-warehouse-picker-neukoelln',
    title: 'Picker / packer',
    company: 'Example fulfilment operator',
    district: 'Neukölln',
    postcode: '12057',
    industryId: 'warehousing',
    roleFamilyId: 'warehouse',
    employmentForms: ['Part-time'],
    language: 'german_explicit',
    listingOrigin: 'sourced',
    compensation: {
      label: '€15 / hour',
      amountMin: 15,
      amountMax: 15,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'not_stated',
      grossNet: 'not_stated',
      extras: null,
    },
    hours: {
      label: '20 hours / week',
      minimum: 20,
      maximum: 20,
      period: 'week',
    },
    schedule: {
      summary: 'Early and late shifts',
      workDays: ['Monday–Saturday'],
      timeWindows: ['06:00–10:00', '17:00–21:00'],
      startDate: 'Immediate start',
      endDate: null,
    },
    workplace: { type: 'on_site', address: '12057 Berlin-Neukölln' },
    responsibilities: [
      'Pick customer orders',
      'Pack and label outgoing goods',
      'Keep stock locations accurate',
    ],
    requirements: [
      'German stated by the source',
      'Able to lift parcels safely',
    ],
    application: {
      method: 'external_link',
      url: '#',
      email: null,
      deadline: null,
      contactName: null,
      instructions: 'Apply on the original employer vacancy page.',
    },
    firstSeenAt: '2026-08-31T18:40:00Z',
    sourceVerifiedAt: '2026-09-01T05:40:00Z',
    sourceKind: 'direct_employer',
    sourceName: 'Example employer vacancy page',
    sourceUrl: '#',
    tags: ['Immediate start', 'Pay stated', 'Shift work'],
    summary: 'Part-time warehouse work across early or late shifts.',
    evidenceNotes: [
      'Employer page names the workplace district',
      'Hourly pay is visible',
      'German requirement is explicit',
    ],
    isDemo: true,
  },
  {
    id: 'preview-4',
    slug: 'sample-hotel-housekeeping-mitte',
    title: 'Housekeeping team member',
    company: 'Example independent hotel',
    district: 'Mitte',
    postcode: '10117',
    industryId: 'hotels',
    roleFamilyId: 'housekeeping',
    employmentForms: ['Part-time'],
    language: 'english_explicit',
    listingOrigin: 'sourced',
    compensation: {
      label: 'Pay not stated',
      amountMin: null,
      amountMax: null,
      currency: 'EUR',
      rateInterval: 'not_stated',
      payoutCadence: 'not_stated',
      grossNet: 'not_stated',
      extras: null,
    },
    hours: {
      label: 'Hours not stated',
      minimum: null,
      maximum: null,
      period: 'not_stated',
    },
    schedule: {
      summary: 'Morning and weekend availability requested',
      workDays: ['Weekdays', 'Weekend'],
      timeWindows: ['Morning'],
      startDate: null,
      endDate: null,
    },
    workplace: { type: 'on_site', address: '10117 Berlin-Mitte' },
    responsibilities: [
      'Clean and prepare guest rooms',
      'Restock room supplies',
      'Report maintenance issues',
    ],
    requirements: [
      'English explicitly accepted',
      'Weekend availability requested',
    ],
    application: {
      method: 'external_link',
      url: '#',
      email: null,
      deadline: null,
      contactName: null,
      instructions: 'Apply on the hotel career page.',
    },
    firstSeenAt: '2026-08-31T15:00:00Z',
    sourceVerifiedAt: '2026-09-01T04:05:00Z',
    sourceKind: 'direct_employer',
    sourceName: 'Example hotel careers page',
    sourceUrl: '#',
    tags: ['English explicitly accepted', 'Weekend'],
    summary: 'Guest-room housekeeping at a central Berlin hotel.',
    evidenceNotes: [
      'Role still live on source at verification time',
      'Berlin property address visible',
      'English explicitly accepted',
    ],
    isDemo: true,
  },
  {
    id: 'preview-5',
    slug: 'sample-retail-sales-charlottenburg',
    title: 'Sales assistant',
    company: 'Example local retailer',
    district: 'Charlottenburg',
    postcode: '10623',
    industryId: 'retail',
    roleFamilyId: 'sales-assistant',
    employmentForms: ['Minijob'],
    language: 'german_explicit',
    listingOrigin: 'employer_posted',
    compensation: {
      label: '€556 / month',
      amountMin: 556,
      amountMax: 556,
      currency: 'EUR',
      rateInterval: 'month',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: 'Employee discount',
    },
    hours: { label: '9 hours / week', minimum: 9, maximum: 9, period: 'week' },
    schedule: {
      summary: 'One weekday afternoon plus Saturday',
      workDays: ['One weekday', 'Saturday'],
      timeWindows: ['Afternoon', '10:00–18:00'],
      startDate: '1 October 2026',
      endDate: null,
    },
    workplace: { type: 'on_site', address: '10623 Berlin-Charlottenburg' },
    responsibilities: [
      'Advise customers',
      'Operate the checkout',
      'Receive and display stock',
    ],
    requirements: [
      'German for customer conversations',
      'Regular Saturday availability',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'retail@example.test',
      deadline: '20 September 2026',
      contactName: 'Example store manager',
      instructions: 'Email a short CV and the weekday afternoons you can work.',
    },
    firstSeenAt: '2026-08-30T10:00:00Z',
    sourceVerifiedAt: '2026-08-31T20:00:00Z',
    sourceKind: 'direct_employer',
    sourceName: 'Posted on JOBROOFS by employer',
    sourceUrl: '#',
    tags: ['Student-friendly', 'Pay stated', 'Saturday'],
    summary: 'A regular weekly Minijob in an independent retail shop.',
    evidenceNotes: [
      'Employer supplied structured pay and hours',
      'Application email requires verification',
      'German requirement explicitly supplied',
    ],
    isDemo: true,
  },
  {
    id: 'preview-6',
    slug: 'sample-museum-visitor-service-tiergarten',
    title: 'Visitor service assistant',
    company: 'Example cultural institution',
    district: 'Tiergarten',
    postcode: '10785',
    industryId: 'culture',
    roleFamilyId: 'service',
    employmentForms: ['Part-time'],
    language: 'german_and_english',
    listingOrigin: 'sourced',
    compensation: {
      label: 'Tariff group stated',
      amountMin: null,
      amountMax: null,
      currency: 'EUR',
      rateInterval: 'month',
      payoutCadence: 'monthly',
      grossNet: 'gross',
      extras: null,
    },
    hours: {
      label: '24 hours / week',
      minimum: 24,
      maximum: 24,
      period: 'week',
    },
    schedule: {
      summary: 'Roster including weekends and public holidays',
      workDays: ['Monday–Sunday by roster'],
      timeWindows: ['Opening hours'],
      startDate: '1 November 2026',
      endDate: '31 October 2027',
    },
    workplace: { type: 'on_site', address: '10785 Berlin-Tiergarten' },
    responsibilities: [
      'Welcome and orient visitors',
      'Check tickets',
      'Support accessibility and venue information',
    ],
    requirements: [
      'German and English stated',
      'Weekend and public-holiday availability',
    ],
    application: {
      method: 'external_link',
      url: '#',
      email: null,
      deadline: '18 September 2026',
      contactName: null,
      instructions: 'Apply through the institution application portal.',
    },
    firstSeenAt: '2026-08-29T09:20:00Z',
    sourceVerifiedAt: '2026-08-31T18:30:00Z',
    sourceKind: 'direct_employer',
    sourceName: 'Example institution careers page',
    sourceUrl: '#',
    tags: ['Weekend', 'Pay stated', 'Fixed-term'],
    summary: 'Visitor support for a Berlin cultural institution.',
    evidenceNotes: [
      'Application deadline visible',
      'Berlin worksite stated',
      'Tariff group captured verbatim',
    ],
    isDemo: true,
  },
  {
    id: 'preview-7',
    slug: 'sample-temp-gallery-shift-mitte',
    title: '1-Day Event Assistant & Setup (Saturday)',
    company: 'Spree Gallery Mitte',
    district: 'Mitte',
    postcode: '10115',
    industryId: 'temp-shifts',
    roleFamilyId: 'temp-cover',
    employmentForms: ['1-day shift / Tagesjob (Single shift)', 'Short-term / Kurzfristige Beschäftigung (Aushilfe)'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    compensation: {
      label: '€18.00 / hour (Paid after shift)',
      amountMin: 18.0,
      amountMax: 18.0,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'after_shift',
      grossNet: 'net',
      extras: 'Free meals & drinks included',
    },
    hours: {
      label: '8 hours (14:00–22:00)',
      minimum: 8,
      maximum: 8,
      period: 'shift',
    },
    schedule: {
      summary: 'Single 1-day shift this Saturday',
      workDays: ['Saturday'],
      timeWindows: ['14:00–22:00'],
      startDate: 'Saturday 12 Oct 2026',
      endDate: 'Saturday 12 Oct 2026',
    },
    workplace: { type: 'on_site', address: 'Torstraße, 10115 Berlin-Mitte' },
    responsibilities: [
      'Assist gallery team with event setup and guest welcome',
      'Check in registered visitors at the entrance desk',
      'Help with drink service and light packdown at end of evening',
    ],
    requirements: [
      'Friendly and presentable manner',
      'Reliable attendance for the full 8-hour shift',
      'English or German communication skills',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'events@spreegallery.example.de',
      deadline: 'Friday 18:00',
      contactName: 'Markus (Gallery Manager)',
      instructions: 'Send a quick WhatsApp or email with your name and confirmation of Saturday availability.',
    },
    firstSeenAt: '2026-09-01T12:00:00Z',
    sourceVerifiedAt: '2026-09-01T12:05:00Z',
    sourceKind: 'direct_employer',
    sourceName: 'Direct gallery post',
    sourceUrl: '#',
    tags: ['1-Day shift', 'Immediate start', 'Paid after shift', 'English accepted'],
    summary: 'Single 1-day Saturday shift for gallery opening in Mitte.',
    evidenceNotes: ['Direct employer posting', 'Immediate payout stated'],
    isDemo: true,
  },
  {
    id: 'preview-8',
    slug: 'sample-home-help-prenzlauerberg',
    title: 'Household Helper & Everyday Support',
    company: 'Private Family Residence',
    district: 'Prenzlauer Berg',
    postcode: '10437',
    industryId: 'home-help',
    roleFamilyId: 'home-help',
    employmentForms: ['Minijob', 'Short-term / Kurzfristige Beschäftigung (Aushilfe)'],
    language: 'german_and_english',
    listingOrigin: 'employer_posted',
    compensation: {
      label: 'To be discussed / Nach Vereinbarung',
      amountMin: null,
      amountMax: null,
      currency: 'EUR',
      rateInterval: 'hour',
      payoutCadence: 'weekly',
      grossNet: 'not_stated',
      extras: 'Flexible hourly rate based on arrangement',
    },
    hours: {
      label: '4–8 hours / week (Flexible)',
      minimum: 4,
      maximum: 8,
      period: 'week',
    },
    schedule: {
      summary: 'Flexible days & times arranged together',
      workDays: ['Flexible / By arrangement'],
      timeWindows: ['Mornings or afternoons'],
      startDate: 'Flexible',
      endDate: null,
    },
    workplace: { type: 'on_site', address: 'Helmholtzplatz, 10437 Berlin' },
    responsibilities: [
      'General household tidying and organization',
      'Occasional grocery runs or light plant watering',
      'Assistance with laundry or seasonal wardrobe sorting',
    ],
    requirements: [
      'Trustworthy, reliable, and neat',
      'Flexible weekly availability',
      'German or English speaking',
    ],
    application: {
      method: 'email',
      url: null,
      email: 'family.prenzlauer@example.de',
      deadline: null,
      contactName: 'Elena',
      instructions: 'Please send a short introduction and your general availability during the week.',
    },
    firstSeenAt: '2026-09-01T14:30:00Z',
    sourceVerifiedAt: '2026-09-01T14:35:00Z',
    sourceKind: 'direct_employer',
    sourceName: 'Direct neighbor post',
    sourceUrl: '#',
    tags: ['Flexible hours', 'No experience needed', 'Student-friendly'],
    summary: 'Flexible household assistance near Helmholtzplatz.',
    evidenceNotes: ['Direct host posting', 'Negotiable schedule'],
    isDemo: true,
  },
];

export const previewSources = [
  {
    name: 'Independent hospitality employers',
    kind: 'Direct employers',
    niches: 'Gastronomy, Hotels',
    cadence: '12h',
    state: 'Adapter queue',
    reason: 'High job turnover; fragmented supply',
  },
  {
    name: 'Berlin venues and event operators',
    kind: 'Direct employers',
    niches: 'Events, Culture, Nightlife',
    cadence: '6h',
    state: 'Adapter queue',
    reason: 'Immediate listings require faster checks',
  },
  {
    name: 'Local retail career pages',
    kind: 'Direct employers',
    niches: 'Retail, Food retail',
    cadence: '24h',
    state: 'Discovery queue',
    reason: 'Many employers never reach large boards',
  },
  {
    name: 'Specialist flexible-work boards',
    kind: 'Specialist boards',
    niches: 'Cross-niche',
    cadence: '24h',
    state: 'Policy review',
    reason: 'Secondary coverage and reconciliation',
  },
  {
    name: 'Large general job boards',
    kind: 'Large boards',
    niches: 'Cross-niche',
    cadence: '48h',
    state: 'Secondary only',
    reason: 'Coverage check, not differentiation',
  },
] as const;
