export type IndustryNiche = {
  id: string;
  label: string;
  labelDe: string;
  description: string;
  sourceTarget: number;
  priority: 'launch' | 'expand' | 'watch';
};

export const industryNiches: IndustryNiche[] = [
  {
    id: 'gastronomy',
    label: 'Gastronomy & cafés',
    labelDe: 'Gastronomie & Cafés',
    description: 'Restaurants, cafés, bakeries and catering teams.',
    sourceTarget: 80,
    priority: 'launch',
  },
  {
    id: 'hotels',
    label: 'Hotels & accommodation',
    labelDe: 'Hotels & Beherbergung',
    description: 'Hotels, hostels, serviced apartments and guest houses.',
    sourceTarget: 45,
    priority: 'launch',
  },
  {
    id: 'events',
    label: 'Events & venues',
    labelDe: 'Events & Veranstaltungsorte',
    description: 'Event crews, venues, trade fairs and temporary productions.',
    sourceTarget: 55,
    priority: 'launch',
  },
  {
    id: 'retail',
    label: 'Retail & shops',
    labelDe: 'Einzelhandel & Shops',
    description: 'Independent shops, chains, fashion and specialty retail.',
    sourceTarget: 70,
    priority: 'launch',
  },
  {
    id: 'food-retail',
    label: 'Supermarkets & food retail',
    labelDe: 'Supermärkte & Lebensmittelhandel',
    description: 'Supermarkets, organic stores, kiosks and food counters.',
    sourceTarget: 45,
    priority: 'launch',
  },
  {
    id: 'warehousing',
    label: 'Warehousing & fulfilment',
    labelDe: 'Lager & Fulfilment',
    description: 'Warehouses, pick-and-pack operations and fulfilment centres.',
    sourceTarget: 40,
    priority: 'launch',
  },
  {
    id: 'logistics',
    label: 'Logistics & delivery',
    labelDe: 'Logistik & Lieferung',
    description: 'Courier, delivery, dispatch and transport operations.',
    sourceTarget: 45,
    priority: 'launch',
  },
  {
    id: 'cleaning',
    label: 'Cleaning & facilities',
    labelDe: 'Reinigung & Facility',
    description: 'Commercial cleaning, housekeeping and building services.',
    sourceTarget: 55,
    priority: 'launch',
  },
  {
    id: 'office-admin',
    label: 'Office & administration',
    labelDe: 'Büro & Verwaltung',
    description: 'Reception, data entry, coordination and office support.',
    sourceTarget: 40,
    priority: 'launch',
  },
  {
    id: 'customer-support',
    label: 'Customer support',
    labelDe: 'Kundenservice',
    description: 'Call centres, service desks and multilingual support.',
    sourceTarget: 30,
    priority: 'expand',
  },
  {
    id: 'sales-promotion',
    label: 'Sales & promotion',
    labelDe: 'Vertrieb & Promotion',
    description: 'Promoters, brand ambassadors and sales support.',
    sourceTarget: 35,
    priority: 'launch',
  },
  {
    id: 'tourism',
    label: 'Tourism & visitor services',
    labelDe: 'Tourismus & Besucherservice',
    description: 'Tours, attractions, ticketing and guest services.',
    sourceTarget: 30,
    priority: 'expand',
  },
  {
    id: 'culture',
    label: 'Culture, museums & theatres',
    labelDe: 'Kultur, Museen & Theater',
    description: 'Front-of-house, visitor and production support.',
    sourceTarget: 35,
    priority: 'expand',
  },
  {
    id: 'nightlife',
    label: 'Nightlife & clubs',
    labelDe: 'Nachtleben & Clubs',
    description: 'Clubs, bars, late venues and door teams.',
    sourceTarget: 35,
    priority: 'launch',
  },
  {
    id: 'sports-fitness',
    label: 'Sports, fitness & recreation',
    labelDe: 'Sport, Fitness & Freizeit',
    description: 'Gyms, studios, pools, clubs and recreation providers.',
    sourceTarget: 35,
    priority: 'expand',
  },
  {
    id: 'childcare-education',
    label: 'Childcare & education support',
    labelDe: 'Kinderbetreuung & Bildung',
    description: 'Kitas, tutoring, language schools and classroom support.',
    sourceTarget: 35,
    priority: 'expand',
  },
  {
    id: 'healthcare-support',
    label: 'Healthcare support',
    labelDe: 'Gesundheitswesen',
    description: 'Non-clinical practice, clinic and patient support roles.',
    sourceTarget: 30,
    priority: 'expand',
  },
  {
    id: 'elder-social-care',
    label: 'Elder care & social services',
    labelDe: 'Pflege & Sozialwesen',
    description: 'Everyday assistance, social organisations and care support.',
    sourceTarget: 35,
    priority: 'expand',
  },
  {
    id: 'security',
    label: 'Security & crowd services',
    labelDe: 'Sicherheit & Einlass',
    description: 'Venue security, access control and event stewarding.',
    sourceTarget: 30,
    priority: 'launch',
  },
  {
    id: 'construction-trades',
    label: 'Construction & trades support',
    labelDe: 'Bau & Handwerkshilfe',
    description: 'Site assistance, workshop support and trades helpers.',
    sourceTarget: 35,
    priority: 'expand',
  },
  {
    id: 'manufacturing',
    label: 'Manufacturing & production',
    labelDe: 'Produktion & Fertigung',
    description: 'Assembly, packing and light production work.',
    sourceTarget: 30,
    priority: 'expand',
  },
  {
    id: 'moving-transport',
    label: 'Moving & transport help',
    labelDe: 'Umzug & Transporthilfe',
    description: 'Moving crews, loading and local transport assistance.',
    sourceTarget: 25,
    priority: 'expand',
  },
  {
    id: 'universities-research',
    label: 'Universities & research',
    labelDe: 'Hochschulen & Forschung',
    description: 'Student assistants, studies and temporary research support.',
    sourceTarget: 30,
    priority: 'expand',
  },
  {
    id: 'ngo-associations',
    label: 'NGOs & associations',
    labelDe: 'NGOs & Vereine',
    description: 'Campaign, member, office and programme support.',
    sourceTarget: 30,
    priority: 'expand',
  },
  {
    id: 'media-creative',
    label: 'Media & creative production',
    labelDe: 'Medien & Kreativproduktion',
    description: 'Shoot, studio, content and production assistance.',
    sourceTarget: 35,
    priority: 'expand',
  },
  {
    id: 'beauty-wellness',
    label: 'Beauty & wellness',
    labelDe: 'Beauty & Wellness',
    description: 'Salons, spas, studios and appointment support.',
    sourceTarget: 30,
    priority: 'expand',
  },
  {
    id: 'pet-care',
    label: 'Pet care',
    labelDe: 'Tierbetreuung',
    description: 'Pet shops, boarding, walking and animal care assistance.',
    sourceTarget: 20,
    priority: 'watch',
  },
  {
    id: 'gardening-outdoor',
    label: 'Gardening & outdoor work',
    labelDe: 'Garten & Außenarbeit',
    description: 'Gardening, grounds, parks and seasonal outdoor support.',
    sourceTarget: 25,
    priority: 'watch',
  },
  {
    id: 'seasonal-markets',
    label: 'Seasonal & markets',
    labelDe: 'Saisonarbeit & Märkte',
    description: 'Christmas markets, festivals, summer and peak-season work.',
    sourceTarget: 35,
    priority: 'launch',
  },
  {
    id: 'temp-shifts',
    label: 'Temp work & 1-day shifts',
    labelDe: 'Tagesjobs & Kurzfristige Einsätze',
    description: '1-day shifts, temp cover, relief staff, spontaneous gigs and immediate single-day work.',
    sourceTarget: 60,
    priority: 'launch',
  },
  {
    id: 'home-help',
    label: 'Home help & everyday assistance',
    labelDe: 'Haushaltshilfe & Alltagshilfe',
    description: 'Household help, cleaning, errands, gardening, moving aid and neighborhood assistance.',
    sourceTarget: 40,
    priority: 'launch',
  },
  {
    id: 'local-services',
    label: 'Other local services',
    labelDe: 'Weitere lokale Dienste',
    description: 'Local flexible work that does not fit a stronger category.',
    sourceTarget: 20,
    priority: 'watch',
  },
];

export const roleFamilies = [
  ['service', 'Service / front of house'],
  ['kitchen', 'Kitchen / food preparation'],
  ['bar', 'Bar staff'],
  ['housekeeping', 'Housekeeping'],
  ['reception', 'Reception'],
  ['warehouse', 'Picker / packer / warehouse'],
  ['delivery', 'Driver / courier'],
  ['cashier', 'Cashier'],
  ['stocking', 'Shelf stacking / stock'],
  ['cleaner', 'Cleaner'],
  ['promoter', 'Promoter / brand ambassador'],
  ['event-crew', 'Event crew'],
  ['office-assistant', 'Office assistant'],
  ['customer-support', 'Customer support'],
  ['sales-assistant', 'Sales assistant'],
  ['care-assistant', 'Care assistant'],
  ['education-assistant', 'Education assistant'],
  ['security', 'Security / steward'],
  ['production-assistant', 'Production assistant'],
  ['trades-helper', 'Trades helper'],
  ['moving-helper', 'Moving helper'],
  ['research-assistant', 'Research assistant'],
  ['content-assistant', 'Content / social media assistant'],
  ['wellness-staff', 'Beauty / wellness staff'],
  ['pet-care', 'Pet care worker'],
  ['gardening', 'Gardening / grounds worker'],
  ['home-help', 'Home help / household assistant'],
  ['temp-cover', 'Temp cover / 1-day shift relief'],
  ['general-aushilfe', 'General Aushilfe'],
] as const;

export const employmentForms = [
  ['minijob', 'Minijob (up to 538€)'],
  ['part-time', 'Part-time / Teilzeit'],
  ['temp-day-shift', '1-day shift / Tagesjob (Single shift)'],
  ['short-term', 'Short-term / Kurzfristige Beschäftigung (Aushilfe)'],
  ['working-student', 'Working student / Werkstudent:in'],
  ['seasonal', 'Seasonal work / Saisonarbeit'],
  ['freelance-gig', 'Freelance / gig'],
  ['on-call', 'On-call / Abrufarbeit'],
  ['internship', 'Paid internship'],
] as const;

export const workConditionTags = [
  'Weekend',
  'Evening',
  'Night shift',
  'Immediate start',
  'No German stated',
  'English explicitly accepted',
  'Pay stated',
  'Tips mentioned',
  'No experience stated',
  'Student-friendly',
  'Shift choice',
  'Accessible workplace stated',
] as const;

export function getIndustry(id: string) {
  return industryNiches.find((niche) => niche.id === id);
}

export function getRoleFamily(id: string) {
  return roleFamilies.find(([roleId]) => roleId === id)?.[1] ?? id;
}
